# ==============================================================================
# Lapis::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  # The `Lapis::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 10 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_INSTALLATION</code></td>
  #       <td><strong>Installation & System Prerequisites</strong></td>
  #       <td>Complete step-by-step setup guide for Crystal, Godot, and Lapis CLI.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_COMPILATION</code></td>
  #       <td><strong>Building Lapis from Source</strong></td>
  #       <td>Compiling the C++ loader bridge, Crystal runtime libraries, and workspace synchronization.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_QUICK_START_TUTORIAL</code></td>
  #       <td><strong>First Game Tutorial (Zero to Hero)</strong></td>
  #       <td>Beginner-friendly step-by-step tutorial: create a project, write a Player node, run, and export.</td>
  #     </tr>
  #     <tr>
  #       <td><code>D_CRYSTAL_BASICS_FOR_GODOT</code></td>
  #       <td><strong>Crystal Syntax Guide for Game Developers</strong></td>
  #       <td>Essential Crystal syntax, static typing, nil-safety, blocks, and official style guides.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 2. Lapis cli and toolchain (`B_LAPIS_CLI_AND_TOOLCHAIN`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_OVERVIEW</code></td>
  #       <td><strong>CLI Architecture & Global Options</strong></td>
  #       <td>Anatomy of the unified lapis executable, global flags, and shell autocompletion.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_DOCTOR</code></td>
  #       <td><strong>Doctor Diagnostic Checker</strong></td>
  #       <td>Comprehensive environment audit checking compilers, runtimes, debuggers, and projects.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_INIT_AND_SCAFFOLD</code></td>
  #       <td><strong>Project Initialization & Scaffolding</strong></td>
  #       <td>Using lapis init, lapis new game, lapis new addon, and lapis new example.</td>
  #     </tr>
  #     <tr>
  #       <td><code>D_BUILD_AND_SYNC</code></td>
  #       <td><strong>Build & Synchronization Commands</strong></td>
  #       <td>Compiling game libraries, plugins, standalone executables, and syncing multi-target projects.</td>
  #     </tr>
  #     <tr>
  #       <td><code>E_TEST_AND_BENCHMARKS</code></td>
  #       <td><strong>Testing Framework & Benchmark Suite</strong></td>
  #       <td>Running the unified multi-phase test runner, interactive ANSI TUI, and performance benchmarks.</td>
  #     </tr>
  #     <tr>
  #       <td><code>F_CLEAN_AND_MAINTENANCE</code></td>
  #       <td><strong>Workspace Cleaning & Disk Reclamation</strong></td>
  #       <td>Using lapis clean, pruning shadow DLLs (--shadows), dry-runs, and directory safety.</td>
  #     </tr>
  #     <tr>
  #       <td><code>G_ADDON_AND_SHARD_MANAGEMENT</code></td>
  #       <td><strong>Addon & Shard Dependency Management</strong></td>
  #       <td>Installing GDExtension addons and managing Crystal shards with lapis addon and lapis shard.</td>
  #     </tr>
  #     <tr>
  #       <td><code>H_IDE_AND_LSP</code></td>
  #       <td><strong>IDE Integration & Language Server (LSP)</strong></td>
  #       <td>Configuring VS Code, Cursor, Zed, and Neovim with Crystalline LSP and radare2 debugging.</td>
  #     </tr>
  #     <tr>
  #       <td><code>I_PACKAGING_AND_DISTRIBUTION</code></td>
  #       <td><strong>Packaging & Release Distribution</strong></td>
  #       <td>Exporting playable standalone games, zip archives, Windows installers, and Debian packages.</td>
  #     </tr>
  #     <tr>
  #       <td><code>J_COMMON_PITFALLS_AND_FAQ</code></td>
  #       <td><strong>Common CLI Pitfalls & Frequently Asked Questions</strong></td>
  #       <td>Solutions to common command-line errors, file locking, path resolution, and developer FAQ.</td>
  #     </tr>
  #     <tr>
  #       <td><code>K_LOGGING_AND_TELEMETRY</code></td>
  #       <td><strong>Logging Framework & Telemetry</strong></td>
  #       <td>Diagnostic logging with Godot.log, custom filters, BBCode console output, compile-time elision, and lapis log.</td>
  #     </tr>
  #     <tr>
  #       <td><code>L_COMPILE_FLAGS_AND_OPTIMIZATION</code></td>
  #       <td><strong>Compile-Time Flags & Optimization</strong></td>
  #       <td>Stripping unused subsystems for lean binaries and enabling opt-in low-overhead diagnostics.</td>
  #     </tr>
  #     <tr>
  #       <td><code>M_ADDON_STORE_AND_SECURITY</code></td>
  #       <td><strong>Addon Store & Security Auditing</strong></td>
  #       <td>Installing, vendoring, updating, and security auditing GDExtension addons.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 3. Gameplay and declarative dsl (`C_GAMEPLAY_AND_DECLARATIVE_DSL`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_NODE_DSL</code></td>
  #       <td><strong>Declarative Node DSL & Lifecycle</strong></td>
  #       <td>Authoring Godot nodes with the node ClassName < ParentNode syntax and virtual methods.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_EXPORTS_AND_INSPECTOR</code></td>
  #       <td><strong>Export System & Inspector Integration</strong></td>
  #       <td>Exposing properties, ranges, enums, file pickers, and tool buttons to the Godot Inspector.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_SIGNALS_AND_EVENTS</code></td>
  #       <td><strong>Signals & Event-Driven Architecture</strong></td>
  #       <td>Declaring signals, synthesized emit helpers, GDScript connections, and cooperative awaiting.</td>
  #     </tr>
  #     <tr>
  #       <td><code>D_LOW_LATENCY_INPUT</code></td>
  #       <td><strong>Low-Latency Input & Controls</strong></td>
  #       <td>Sub-frame mouse look, zero-allocation input queries, unhandled input, and input maps.</td>
  #     </tr>
  #     <tr>
  #       <td><code>E_SCENE_TREE_AND_LIFECYCLE</code></td>
  #       <td><strong>Scene Tree Manipulation & Node Lifecycle</strong></td>
  #       <td>Creating nodes (Godot.create), hierarchy management, node ownership, and clean deletion.</td>
  #     </tr>
  #     <tr>
  #       <td><code>F_GAMEPLAY_LOGGING_AND_SENSORS</code></td>
  #       <td><strong>Gameplay Logging & Diagnostics DSL</strong></td>
  #       <td>Integrating structured logging, gameplay metrics, and tag filters within Godot nodes.</td>
  #     </tr>
  #     <tr>
  #       <td><code>G_ERGONOMIC_NODE_ACCESS</code></td>
  #       <td><strong>Ergonomic Node & Path Access</strong></td>
  #       <td>Type-safe node retrieval, subscript indexers ([]), operator overloads (/ and %), path prefixes ($ and %), and bare macros (n! and u!).</td>
  #     </tr>
  #     <tr>
  #       <td><code>H_MODULES_AND_MIXINS</code></td>
  #       <td><strong>Modular Node Mixins (gmodule)</strong></td>
  #       <td>Authoring reusable gameplay traits, interfaces, and component mixins with export properties, signals, and lifecycle hooks.</td>
  #     </tr>
  #     <tr>
  #       <td><code>I_MULTIPLAYER_AND_NETWORKING</code></td>
  #       <td><strong>Multiplayer and Networking</strong></td>
  #       <td>High-performance multiplayer networking, declarative @[RPC] annotations, synchronization DSL, and Wireshark-style network testing harness.</td>
  #     </tr>
  #     <tr>
  #       <td><code>J_GDSCRIPT_TO_CRYSTAL_CHEATSHEET</code></td>
  #       <td><strong>GDScript to Crystal Migration Cheatsheet</strong></td>
  #       <td>Exhaustive side-by-side cheatsheet mapping GDScript syntax to Crystal for Lapis.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 4. Concurrency and fibers (`D_CONCURRENCY_AND_FIBERS`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_FIBERS_AND_COOPERATIVE_AWAIT</code></td>
  #       <td><strong>Fibers & Cooperative Signal Awaiting</strong></td>
  #       <td>Single-threaded scene loop orchestration, Fiber.yield, and non-blocking timers.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_OS_THREADS_AND_CHANNELS</code></td>
  #       <td><strong>OS Threads & Actor Channels</strong></td>
  #       <td>Offloading intensive computing with Thread.new and buffered Godot::Channel(T).</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_MAIN_THREAD_DISPATCH</code></td>
  #       <td><strong>Main Thread Queue & Thread-Safe Dispatch</strong></td>
  #       <td>Modifying scenes from workers via Godot.on_main_thread, call_deferred, and thread asserts.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 5. Memory safety and engine internals (`E_MEMORY_SAFETY_AND_ENGINE_INTERNALS`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_OBJECTDB_AND_MONOTONIC_IDS</code></td>
  #       <td><strong>Godot ObjectDB & Monotonic Instance IDs</strong></td>
  #       <td>Mapping native C++ heap pointers to 64-bit monotonic instance IDs to prevent pointer reuse.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_DEAD_POINTER_PROTECTION</code></td>
  #       <td><strong>Dead-Pointer Protection & Access Violation Defense</strong></td>
  #       <td>Defensive inspection (#alive?, #destroyed?, #check_alive!) and DisposedObjectError.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_BOEHM_GC_VS_REFCOUNTING</code></td>
  #       <td><strong>Boehm GC vs Godot Reference Counting</strong></td>
  #       <td>Bridging Crystal's garbage collector and Godot's atomic reference counter.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 6. Scripting and interoperability (`F_SCRIPTING_AND_INTEROPERABILITY`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_FIRST_CLASS_CRYSTAL_SCRIPTS</code></td>
  #       <td><strong>First-Class Crystal Scripts in Godot Editor</strong></td>
  #       <td>Writing .cr files directly inside Godot Script Editor with native syntax highlighting and Crystalline LSP.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_GDSCRIPT_INTEROP</code></td>
  #       <td><strong>GDScript Interoperability & Project Bindings</strong></td>
  #       <td>Bidirectional calling between Crystal and GDScript, automated typed wrappers, and Variant marshaling.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_DOC_COMMENTS_AND_F1_HELP</code></td>
  #       <td><strong>Doc Comments & Godot In-Editor F1 Help</strong></td>
  #       <td>Compile-time doc comment harvesting, DocData XML synthesis, and Godot offline documentation.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 7. Debugging and diagnostics (`G_DEBUGGING_AND_DIAGNOSTICS`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_RADARE2_NATIVE_DEBUGGING</code></td>
  #       <td><strong>Native radare2 Debugging, Decompilation & Gutter Breakpoints</strong></td>
  #       <td>Attaching radare2 to Godot processes, native pseudo-C decompilation (pdc), disassembly, and multiplayer lockstep.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_CRASH_HANDLER_AND_WATCHPOINTS</code></td>
  #       <td><strong>Crash Diagnostics, Watchpoints & Memory Inspection</strong></td>
  #       <td>Debugging segmentation faults (0xC0000005), hardware watchpoints, and dead-pointer forensics.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_LEAK_AND_DISPATCH_DIAGNOSTICS</code></td>
  #       <td><strong>Leak Tracking & Latency Profiling</strong></td>
  #       <td>Using LeakTracker, TombstoneTracker, and DispatchProfiler for runtime introspection.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 8. Testing and benchmarks (`H_TESTING_AND_BENCHMARKS`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_TESTING_FRAMEWORK</code></td>
  #       <td><strong>Unified Testing Framework & Leak Verification</strong></td>
  #       <td>Writing test suites, assertions, frame-stepping, and zero memory leak validation (assert_no_leak).</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_PERFORMANCE_BENCHMARKS</code></td>
  #       <td><strong>Performance Profiling & Benchmark Reports</strong></td>
  #       <td>Running Crystal vs GDScript benchmarks, SVG chart generation, and CI tracking.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 9. Architecture and extensions (`I_ARCHITECTURE_AND_EXTENSIONS`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_DUAL_PARADIGM_MODEL</code></td>
  #       <td><strong>The Dual-Paradigm Execution Model</strong></td>
  #       <td>Mode A (GDExtension In-Editor Tool) vs Mode B (Standalone LibGodot Host Executable).</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_CPP_BRIDGE_LOADER</code></td>
  #       <td><strong>Native C++ Loader Bridge Architecture</strong></td>
  #       <td>Flat C-ABI mapping, GDExtension function pointers, memory layouts, and crash guards.</td>
  #     </tr>
  #     <tr>
  #       <td><code>C_ADDONS_AND_MULTI_PLUGIN_ISOLATION</code></td>
  #       <td><strong>GDExtension Addons & Multi-Plugin Isolation</strong></td>
  #       <td>ClassDB namespace isolation, inter-addon dependencies, and compilation topologies across Crystal addons.</td>
  #     </tr>
  #     <tr>
  #       <td><code>D_GODOT_VERSION_UPGRADE</code></td>
  #       <td><strong>Godot Engine Version Upgrade Guide</strong></td>
  #       <td>Upgrading target Godot versions, dumping extension_api.json, and regenerating Crystal class bindings.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 10. Modern cli and tui (`J_MODERN_CLI_AND_TUI`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_INTERACTIVE_COMMAND_CENTER</code></td>
  #       <td><strong>Interactive Terminal Command Center & Differential TUI</strong></td>
  #       <td>High-density telemetry dashboard, split-pane layout, differential cell rendering, and keyboard shortcuts.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_TUI_HUB_AND_SPECIALIZED_VIEWS</code></td>
  #       <td><strong>Interactive TUI Hub & Domain Workspaces</strong></td>
  #       <td>Operational guide to lapis cli hub, folder-picker new/editor wizards, context-aware package forms, r2 crash forensics, and benchmark analytics.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Lapis Quick Start:
    # ```bash
    # lapis doctor     # Diagnose developer environment & dependencies
    # lapis new game   # Scaffold brand new Crystal Godot game
    # make all         # Compile bridge, test suites, examples, and sync
    # make test        # Execute specs, in-editor tool tests, and runtime suites
    # make editor      # Launch test project in Godot Editor
    # make docs        # Build offline HTML documentation site in docs/
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::A_INSTALLATION`: **Installation & System Prerequisites** &mdash; Complete step-by-step setup guide for Crystal, Godot, and Lapis CLI.
    # - `A_GETTING_STARTED::B_COMPILATION`: **Building Lapis from Source** &mdash; Compiling the C++ loader bridge, Crystal runtime libraries, and workspace synchronization.
    # - `A_GETTING_STARTED::C_QUICK_START_TUTORIAL`: **First Game Tutorial (Zero to Hero)** &mdash; Beginner-friendly step-by-step tutorial: create a project, write a Player node, run, and export.
    # - `A_GETTING_STARTED::D_CRYSTAL_BASICS_FOR_GODOT`: **Crystal Syntax Guide for Game Developers** &mdash; Essential Crystal syntax, static typing, nil-safety, blocks, and official style guides.
    #
    # ##### 2. Lapis cli and toolchain (`B_LAPIS_CLI_AND_TOOLCHAIN`)
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::A_OVERVIEW`: **CLI Architecture & Global Options** &mdash; Anatomy of the unified lapis executable, global flags, and shell autocompletion.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::B_DOCTOR`: **Doctor Diagnostic Checker** &mdash; Comprehensive environment audit checking compilers, runtimes, debuggers, and projects.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::C_INIT_AND_SCAFFOLD`: **Project Initialization & Scaffolding** &mdash; Using lapis init, lapis new game, lapis new addon, and lapis new example.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::D_BUILD_AND_SYNC`: **Build & Synchronization Commands** &mdash; Compiling game libraries, plugins, standalone executables, and syncing multi-target projects.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::E_TEST_AND_BENCHMARKS`: **Testing Framework & Benchmark Suite** &mdash; Running the unified multi-phase test runner, interactive ANSI TUI, and performance benchmarks.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::F_CLEAN_AND_MAINTENANCE`: **Workspace Cleaning & Disk Reclamation** &mdash; Using lapis clean, pruning shadow DLLs (--shadows), dry-runs, and directory safety.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::G_ADDON_AND_SHARD_MANAGEMENT`: **Addon & Shard Dependency Management** &mdash; Installing GDExtension addons and managing Crystal shards with lapis addon and lapis shard.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::H_IDE_AND_LSP`: **IDE Integration & Language Server (LSP)** &mdash; Configuring VS Code, Cursor, Zed, and Neovim with Crystalline LSP and radare2 debugging.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::I_PACKAGING_AND_DISTRIBUTION`: **Packaging & Release Distribution** &mdash; Exporting playable standalone games, zip archives, Windows installers, and Debian packages.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::J_COMMON_PITFALLS_AND_FAQ`: **Common CLI Pitfalls & Frequently Asked Questions** &mdash; Solutions to common command-line errors, file locking, path resolution, and developer FAQ.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::K_LOGGING_AND_TELEMETRY`: **Logging Framework & Telemetry** &mdash; Diagnostic logging with Godot.log, custom filters, BBCode console output, compile-time elision, and lapis log.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::L_COMPILE_FLAGS_AND_OPTIMIZATION`: **Compile-Time Flags & Optimization** &mdash; Stripping unused subsystems for lean binaries and enabling opt-in low-overhead diagnostics.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::M_ADDON_STORE_AND_SECURITY`: **Addon Store & Security Auditing** &mdash; Installing, vendoring, updating, and security auditing GDExtension addons.
    #
    # ##### 3. Gameplay and declarative dsl (`C_GAMEPLAY_AND_DECLARATIVE_DSL`)
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::A_NODE_DSL`: **Declarative Node DSL & Lifecycle** &mdash; Authoring Godot nodes with the node ClassName &lt; ParentNode syntax and virtual methods.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::B_EXPORTS_AND_INSPECTOR`: **Export System & Inspector Integration** &mdash; Exposing properties, ranges, enums, file pickers, and tool buttons to the Godot Inspector.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::C_SIGNALS_AND_EVENTS`: **Signals & Event-Driven Architecture** &mdash; Declaring signals, synthesized emit helpers, GDScript connections, and cooperative awaiting.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::D_LOW_LATENCY_INPUT`: **Low-Latency Input & Controls** &mdash; Sub-frame mouse look, zero-allocation input queries, unhandled input, and input maps.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::E_SCENE_TREE_AND_LIFECYCLE`: **Scene Tree Manipulation & Node Lifecycle** &mdash; Creating nodes (Godot.create), hierarchy management, node ownership, and clean deletion.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::F_GAMEPLAY_LOGGING_AND_SENSORS`: **Gameplay Logging & Diagnostics DSL** &mdash; Integrating structured logging, gameplay metrics, and tag filters within Godot nodes.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::G_ERGONOMIC_NODE_ACCESS`: **Ergonomic Node & Path Access** &mdash; Type-safe node retrieval, subscript indexers ([]), operator overloads (/ and %), path prefixes ($ and %), and bare macros (n! and u!).
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::H_MODULES_AND_MIXINS`: **Modular Node Mixins (gmodule)** &mdash; Authoring reusable gameplay traits, interfaces, and component mixins with export properties, signals, and lifecycle hooks.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::I_MULTIPLAYER_AND_NETWORKING`: **Multiplayer and Networking** &mdash; High-performance multiplayer networking, declarative @[RPC] annotations, synchronization DSL, and Wireshark-style network testing harness.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::J_GDSCRIPT_TO_CRYSTAL_CHEATSHEET`: **GDScript to Crystal Migration Cheatsheet** &mdash; Exhaustive side-by-side cheatsheet mapping GDScript syntax to Crystal for Lapis.
    #
    # ##### 4. Concurrency and fibers (`D_CONCURRENCY_AND_FIBERS`)
    # - `D_CONCURRENCY_AND_FIBERS::A_FIBERS_AND_COOPERATIVE_AWAIT`: **Fibers & Cooperative Signal Awaiting** &mdash; Single-threaded scene loop orchestration, Fiber.yield, and non-blocking timers.
    # - `D_CONCURRENCY_AND_FIBERS::B_OS_THREADS_AND_CHANNELS`: **OS Threads & Actor Channels** &mdash; Offloading intensive computing with Thread.new and buffered Godot::Channel(T).
    # - `D_CONCURRENCY_AND_FIBERS::C_MAIN_THREAD_DISPATCH`: **Main Thread Queue & Thread-Safe Dispatch** &mdash; Modifying scenes from workers via Godot.on_main_thread, call_deferred, and thread asserts.
    #
    # ##### 5. Memory safety and engine internals (`E_MEMORY_SAFETY_AND_ENGINE_INTERNALS`)
    # - `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS::A_OBJECTDB_AND_MONOTONIC_IDS`: **Godot ObjectDB & Monotonic Instance IDs** &mdash; Mapping native C++ heap pointers to 64-bit monotonic instance IDs to prevent pointer reuse.
    # - `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS::B_DEAD_POINTER_PROTECTION`: **Dead-Pointer Protection & Access Violation Defense** &mdash; Defensive inspection (#alive?, #destroyed?, #check_alive!) and DisposedObjectError.
    # - `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS::C_BOEHM_GC_VS_REFCOUNTING`: **Boehm GC vs Godot Reference Counting** &mdash; Bridging Crystal's garbage collector and Godot's atomic reference counter.
    #
    # ##### 6. Scripting and interoperability (`F_SCRIPTING_AND_INTEROPERABILITY`)
    # - `F_SCRIPTING_AND_INTEROPERABILITY::A_FIRST_CLASS_CRYSTAL_SCRIPTS`: **First-Class Crystal Scripts in Godot Editor** &mdash; Writing .cr files directly inside Godot Script Editor with native syntax highlighting and Crystalline LSP.
    # - `F_SCRIPTING_AND_INTEROPERABILITY::B_GDSCRIPT_INTEROP`: **GDScript Interoperability & Project Bindings** &mdash; Bidirectional calling between Crystal and GDScript, automated typed wrappers, and Variant marshaling.
    # - `F_SCRIPTING_AND_INTEROPERABILITY::C_DOC_COMMENTS_AND_F1_HELP`: **Doc Comments & Godot In-Editor F1 Help** &mdash; Compile-time doc comment harvesting, DocData XML synthesis, and Godot offline documentation.
    #
    # ##### 7. Debugging and diagnostics (`G_DEBUGGING_AND_DIAGNOSTICS`)
    # - `G_DEBUGGING_AND_DIAGNOSTICS::A_RADARE2_NATIVE_DEBUGGING`: **Native radare2 Debugging, Decompilation & Gutter Breakpoints** &mdash; Attaching radare2 to Godot processes, native pseudo-C decompilation (pdc), disassembly, and multiplayer lockstep.
    # - `G_DEBUGGING_AND_DIAGNOSTICS::B_CRASH_HANDLER_AND_WATCHPOINTS`: **Crash Diagnostics, Watchpoints & Memory Inspection** &mdash; Debugging segmentation faults (0xC0000005), hardware watchpoints, and dead-pointer forensics.
    # - `G_DEBUGGING_AND_DIAGNOSTICS::C_LEAK_AND_DISPATCH_DIAGNOSTICS`: **Leak Tracking & Latency Profiling** &mdash; Using LeakTracker, TombstoneTracker, and DispatchProfiler for runtime introspection.
    #
    # ##### 8. Testing and benchmarks (`H_TESTING_AND_BENCHMARKS`)
    # - `H_TESTING_AND_BENCHMARKS::A_TESTING_FRAMEWORK`: **Unified Testing Framework & Leak Verification** &mdash; Writing test suites, assertions, frame-stepping, and zero memory leak validation (assert_no_leak).
    # - `H_TESTING_AND_BENCHMARKS::B_PERFORMANCE_BENCHMARKS`: **Performance Profiling & Benchmark Reports** &mdash; Running Crystal vs GDScript benchmarks, SVG chart generation, and CI tracking.
    #
    # ##### 9. Architecture and extensions (`I_ARCHITECTURE_AND_EXTENSIONS`)
    # - `I_ARCHITECTURE_AND_EXTENSIONS::A_DUAL_PARADIGM_MODEL`: **The Dual-Paradigm Execution Model** &mdash; Mode A (GDExtension In-Editor Tool) vs Mode B (Standalone LibGodot Host Executable).
    # - `I_ARCHITECTURE_AND_EXTENSIONS::B_CPP_BRIDGE_LOADER`: **Native C++ Loader Bridge Architecture** &mdash; Flat C-ABI mapping, GDExtension function pointers, memory layouts, and crash guards.
    # - `I_ARCHITECTURE_AND_EXTENSIONS::C_ADDONS_AND_MULTI_PLUGIN_ISOLATION`: **GDExtension Addons & Multi-Plugin Isolation** &mdash; ClassDB namespace isolation, inter-addon dependencies, and compilation topologies across Crystal addons.
    # - `I_ARCHITECTURE_AND_EXTENSIONS::D_GODOT_VERSION_UPGRADE`: **Godot Engine Version Upgrade Guide** &mdash; Upgrading target Godot versions, dumping extension_api.json, and regenerating Crystal class bindings.
    #
    # ##### 10. Modern cli and tui (`J_MODERN_CLI_AND_TUI`)
    # - `J_MODERN_CLI_AND_TUI::A_INTERACTIVE_COMMAND_CENTER`: **Interactive Terminal Command Center & Differential TUI** &mdash; High-density telemetry dashboard, split-pane layout, differential cell rendering, and keyboard shortcuts.
    # - `J_MODERN_CLI_AND_TUI::B_TUI_HUB_AND_SPECIALIZED_VIEWS`: **Interactive TUI Hub & Domain Workspaces** &mdash; Operational guide to lapis cli hub, folder-picker new/editor wizards, context-aware package forms, r2 crash forensics, and benchmark analytics.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::A_INSTALLATION`: **Installation & System Prerequisites** &mdash; Complete step-by-step setup guide for Crystal, Godot, and Lapis CLI.
    # - `A_GETTING_STARTED::B_COMPILATION`: **Building Lapis from Source** &mdash; Compiling the C++ loader bridge, Crystal runtime libraries, and workspace synchronization.
    # - `A_GETTING_STARTED::C_QUICK_START_TUTORIAL`: **First Game Tutorial (Zero to Hero)** &mdash; Beginner-friendly step-by-step tutorial: create a project, write a Player node, run, and export.
    # - `A_GETTING_STARTED::D_CRYSTAL_BASICS_FOR_GODOT`: **Crystal Syntax Guide for Game Developers** &mdash; Essential Crystal syntax, static typing, nil-safety, blocks, and official style guides.
    #
    # ##### `B_LAPIS_CLI_AND_TOOLCHAIN`
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::A_OVERVIEW`: **CLI Architecture & Global Options** &mdash; Anatomy of the unified lapis executable, global flags, and shell autocompletion.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::B_DOCTOR`: **Doctor Diagnostic Checker** &mdash; Comprehensive environment audit checking compilers, runtimes, debuggers, and projects.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::C_INIT_AND_SCAFFOLD`: **Project Initialization & Scaffolding** &mdash; Using lapis init, lapis new game, lapis new addon, and lapis new example.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::D_BUILD_AND_SYNC`: **Build & Synchronization Commands** &mdash; Compiling game libraries, plugins, standalone executables, and syncing multi-target projects.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::E_TEST_AND_BENCHMARKS`: **Testing Framework & Benchmark Suite** &mdash; Running the unified multi-phase test runner, interactive ANSI TUI, and performance benchmarks.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::F_CLEAN_AND_MAINTENANCE`: **Workspace Cleaning & Disk Reclamation** &mdash; Using lapis clean, pruning shadow DLLs (--shadows), dry-runs, and directory safety.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::G_ADDON_AND_SHARD_MANAGEMENT`: **Addon & Shard Dependency Management** &mdash; Installing GDExtension addons and managing Crystal shards with lapis addon and lapis shard.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::H_IDE_AND_LSP`: **IDE Integration & Language Server (LSP)** &mdash; Configuring VS Code, Cursor, Zed, and Neovim with Crystalline LSP and radare2 debugging.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::I_PACKAGING_AND_DISTRIBUTION`: **Packaging & Release Distribution** &mdash; Exporting playable standalone games, zip archives, Windows installers, and Debian packages.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::J_COMMON_PITFALLS_AND_FAQ`: **Common CLI Pitfalls & Frequently Asked Questions** &mdash; Solutions to common command-line errors, file locking, path resolution, and developer FAQ.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::K_LOGGING_AND_TELEMETRY`: **Logging Framework & Telemetry** &mdash; Diagnostic logging with Godot.log, custom filters, BBCode console output, compile-time elision, and lapis log.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::L_COMPILE_FLAGS_AND_OPTIMIZATION`: **Compile-Time Flags & Optimization** &mdash; Stripping unused subsystems for lean binaries and enabling opt-in low-overhead diagnostics.
    # - `B_LAPIS_CLI_AND_TOOLCHAIN::M_ADDON_STORE_AND_SECURITY`: **Addon Store & Security Auditing** &mdash; Installing, vendoring, updating, and security auditing GDExtension addons.
    #
    # ##### `C_GAMEPLAY_AND_DECLARATIVE_DSL`
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::A_NODE_DSL`: **Declarative Node DSL & Lifecycle** &mdash; Authoring Godot nodes with the node ClassName &lt; ParentNode syntax and virtual methods.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::B_EXPORTS_AND_INSPECTOR`: **Export System & Inspector Integration** &mdash; Exposing properties, ranges, enums, file pickers, and tool buttons to the Godot Inspector.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::C_SIGNALS_AND_EVENTS`: **Signals & Event-Driven Architecture** &mdash; Declaring signals, synthesized emit helpers, GDScript connections, and cooperative awaiting.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::D_LOW_LATENCY_INPUT`: **Low-Latency Input & Controls** &mdash; Sub-frame mouse look, zero-allocation input queries, unhandled input, and input maps.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::E_SCENE_TREE_AND_LIFECYCLE`: **Scene Tree Manipulation & Node Lifecycle** &mdash; Creating nodes (Godot.create), hierarchy management, node ownership, and clean deletion.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::F_GAMEPLAY_LOGGING_AND_SENSORS`: **Gameplay Logging & Diagnostics DSL** &mdash; Integrating structured logging, gameplay metrics, and tag filters within Godot nodes.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::G_ERGONOMIC_NODE_ACCESS`: **Ergonomic Node & Path Access** &mdash; Type-safe node retrieval, subscript indexers ([]), operator overloads (/ and %), path prefixes ($ and %), and bare macros (n! and u!).
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::H_MODULES_AND_MIXINS`: **Modular Node Mixins (gmodule)** &mdash; Authoring reusable gameplay traits, interfaces, and component mixins with export properties, signals, and lifecycle hooks.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::I_MULTIPLAYER_AND_NETWORKING`: **Multiplayer and Networking** &mdash; High-performance multiplayer networking, declarative @[RPC] annotations, synchronization DSL, and Wireshark-style network testing harness.
    # - `C_GAMEPLAY_AND_DECLARATIVE_DSL::J_GDSCRIPT_TO_CRYSTAL_CHEATSHEET`: **GDScript to Crystal Migration Cheatsheet** &mdash; Exhaustive side-by-side cheatsheet mapping GDScript syntax to Crystal for Lapis.
    #
    # ##### `D_CONCURRENCY_AND_FIBERS`
    # - `D_CONCURRENCY_AND_FIBERS::A_FIBERS_AND_COOPERATIVE_AWAIT`: **Fibers & Cooperative Signal Awaiting** &mdash; Single-threaded scene loop orchestration, Fiber.yield, and non-blocking timers.
    # - `D_CONCURRENCY_AND_FIBERS::B_OS_THREADS_AND_CHANNELS`: **OS Threads & Actor Channels** &mdash; Offloading intensive computing with Thread.new and buffered Godot::Channel(T).
    # - `D_CONCURRENCY_AND_FIBERS::C_MAIN_THREAD_DISPATCH`: **Main Thread Queue & Thread-Safe Dispatch** &mdash; Modifying scenes from workers via Godot.on_main_thread, call_deferred, and thread asserts.
    #
    # ##### `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS`
    # - `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS::A_OBJECTDB_AND_MONOTONIC_IDS`: **Godot ObjectDB & Monotonic Instance IDs** &mdash; Mapping native C++ heap pointers to 64-bit monotonic instance IDs to prevent pointer reuse.
    # - `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS::B_DEAD_POINTER_PROTECTION`: **Dead-Pointer Protection & Access Violation Defense** &mdash; Defensive inspection (#alive?, #destroyed?, #check_alive!) and DisposedObjectError.
    # - `E_MEMORY_SAFETY_AND_ENGINE_INTERNALS::C_BOEHM_GC_VS_REFCOUNTING`: **Boehm GC vs Godot Reference Counting** &mdash; Bridging Crystal's garbage collector and Godot's atomic reference counter.
    #
    # ##### `F_SCRIPTING_AND_INTEROPERABILITY`
    # - `F_SCRIPTING_AND_INTEROPERABILITY::A_FIRST_CLASS_CRYSTAL_SCRIPTS`: **First-Class Crystal Scripts in Godot Editor** &mdash; Writing .cr files directly inside Godot Script Editor with native syntax highlighting and Crystalline LSP.
    # - `F_SCRIPTING_AND_INTEROPERABILITY::B_GDSCRIPT_INTEROP`: **GDScript Interoperability & Project Bindings** &mdash; Bidirectional calling between Crystal and GDScript, automated typed wrappers, and Variant marshaling.
    # - `F_SCRIPTING_AND_INTEROPERABILITY::C_DOC_COMMENTS_AND_F1_HELP`: **Doc Comments & Godot In-Editor F1 Help** &mdash; Compile-time doc comment harvesting, DocData XML synthesis, and Godot offline documentation.
    #
    # ##### `G_DEBUGGING_AND_DIAGNOSTICS`
    # - `G_DEBUGGING_AND_DIAGNOSTICS::A_RADARE2_NATIVE_DEBUGGING`: **Native radare2 Debugging, Decompilation & Gutter Breakpoints** &mdash; Attaching radare2 to Godot processes, native pseudo-C decompilation (pdc), disassembly, and multiplayer lockstep.
    # - `G_DEBUGGING_AND_DIAGNOSTICS::B_CRASH_HANDLER_AND_WATCHPOINTS`: **Crash Diagnostics, Watchpoints & Memory Inspection** &mdash; Debugging segmentation faults (0xC0000005), hardware watchpoints, and dead-pointer forensics.
    # - `G_DEBUGGING_AND_DIAGNOSTICS::C_LEAK_AND_DISPATCH_DIAGNOSTICS`: **Leak Tracking & Latency Profiling** &mdash; Using LeakTracker, TombstoneTracker, and DispatchProfiler for runtime introspection.
    #
    # ##### `H_TESTING_AND_BENCHMARKS`
    # - `H_TESTING_AND_BENCHMARKS::A_TESTING_FRAMEWORK`: **Unified Testing Framework & Leak Verification** &mdash; Writing test suites, assertions, frame-stepping, and zero memory leak validation (assert_no_leak).
    # - `H_TESTING_AND_BENCHMARKS::B_PERFORMANCE_BENCHMARKS`: **Performance Profiling & Benchmark Reports** &mdash; Running Crystal vs GDScript benchmarks, SVG chart generation, and CI tracking.
    #
    # ##### `I_ARCHITECTURE_AND_EXTENSIONS`
    # - `I_ARCHITECTURE_AND_EXTENSIONS::A_DUAL_PARADIGM_MODEL`: **The Dual-Paradigm Execution Model** &mdash; Mode A (GDExtension In-Editor Tool) vs Mode B (Standalone LibGodot Host Executable).
    # - `I_ARCHITECTURE_AND_EXTENSIONS::B_CPP_BRIDGE_LOADER`: **Native C++ Loader Bridge Architecture** &mdash; Flat C-ABI mapping, GDExtension function pointers, memory layouts, and crash guards.
    # - `I_ARCHITECTURE_AND_EXTENSIONS::C_ADDONS_AND_MULTI_PLUGIN_ISOLATION`: **GDExtension Addons & Multi-Plugin Isolation** &mdash; ClassDB namespace isolation, inter-addon dependencies, and compilation topologies across Crystal addons.
    # - `I_ARCHITECTURE_AND_EXTENSIONS::D_GODOT_VERSION_UPGRADE`: **Godot Engine Version Upgrade Guide** &mdash; Upgrading target Godot versions, dumping extension_api.json, and regenerating Crystal class bindings.
    #
    # ##### `J_MODERN_CLI_AND_TUI`
    # - `J_MODERN_CLI_AND_TUI::A_INTERACTIVE_COMMAND_CENTER`: **Interactive Terminal Command Center & Differential TUI** &mdash; High-density telemetry dashboard, split-pane layout, differential cell rendering, and keyboard shortcuts.
    # - `J_MODERN_CLI_AND_TUI::B_TUI_HUB_AND_SPECIALIZED_VIEWS`: **Interactive TUI Hub & Domain Workspaces** &mdash; Operational guide to lapis cli hub, folder-picker new/editor wizards, context-aware package forms, r2 crash forensics, and benchmark analytics.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/a_installation"
require "./docs/a_getting_started/b_compilation"
require "./docs/a_getting_started/c_quick_start_tutorial"
require "./docs/a_getting_started/d_crystal_basics_for_godot"
require "./docs/b_lapis_cli_and_toolchain/a_overview"
require "./docs/b_lapis_cli_and_toolchain/b_doctor"
require "./docs/b_lapis_cli_and_toolchain/c_init_and_scaffold"
require "./docs/b_lapis_cli_and_toolchain/d_build_and_sync"
require "./docs/b_lapis_cli_and_toolchain/e_test_and_benchmarks"
require "./docs/b_lapis_cli_and_toolchain/f_clean_and_maintenance"
require "./docs/b_lapis_cli_and_toolchain/g_addon_and_shard_management"
require "./docs/b_lapis_cli_and_toolchain/h_ide_and_lsp"
require "./docs/b_lapis_cli_and_toolchain/i_packaging_and_distribution"
require "./docs/b_lapis_cli_and_toolchain/j_common_pitfalls_and_faq"
require "./docs/b_lapis_cli_and_toolchain/k_logging_and_telemetry"
require "./docs/b_lapis_cli_and_toolchain/l_compile_flags_and_optimization"
require "./docs/b_lapis_cli_and_toolchain/m_addon_store_and_security"
require "./docs/c_gameplay_and_declarative_dsl/a_node_dsl"
require "./docs/c_gameplay_and_declarative_dsl/b_exports_and_inspector"
require "./docs/c_gameplay_and_declarative_dsl/c_signals_and_events"
require "./docs/c_gameplay_and_declarative_dsl/d_low_latency_input"
require "./docs/c_gameplay_and_declarative_dsl/e_scene_tree_and_lifecycle"
require "./docs/c_gameplay_and_declarative_dsl/f_gameplay_logging_and_sensors"
require "./docs/c_gameplay_and_declarative_dsl/g_ergonomic_node_access"
require "./docs/c_gameplay_and_declarative_dsl/h_modules_and_mixins"
require "./docs/c_gameplay_and_declarative_dsl/i_multiplayer_and_networking"
require "./docs/c_gameplay_and_declarative_dsl/j_gdscript_to_crystal_cheatsheet"
require "./docs/d_concurrency_and_fibers/a_fibers_and_cooperative_await"
require "./docs/d_concurrency_and_fibers/b_os_threads_and_channels"
require "./docs/d_concurrency_and_fibers/c_main_thread_dispatch"
require "./docs/e_memory_safety_and_engine_internals/a_objectdb_and_monotonic_ids"
require "./docs/e_memory_safety_and_engine_internals/b_dead_pointer_protection"
require "./docs/e_memory_safety_and_engine_internals/c_boehm_gc_vs_refcounting"
require "./docs/f_scripting_and_interoperability/a_first_class_crystal_scripts"
require "./docs/f_scripting_and_interoperability/b_gdscript_interop"
require "./docs/f_scripting_and_interoperability/c_doc_comments_and_f1_help"
require "./docs/g_debugging_and_diagnostics/a_radare2_native_debugging"
require "./docs/g_debugging_and_diagnostics/b_crash_handler_and_watchpoints"
require "./docs/g_debugging_and_diagnostics/c_leak_and_dispatch_diagnostics"
require "./docs/h_testing_and_benchmarks/a_testing_framework"
require "./docs/h_testing_and_benchmarks/b_performance_benchmarks"
require "./docs/i_architecture_and_extensions/a_dual_paradigm_model"
require "./docs/i_architecture_and_extensions/b_cpp_bridge_loader"
require "./docs/i_architecture_and_extensions/c_addons_and_multi_plugin_isolation"
require "./docs/i_architecture_and_extensions/d_godot_version_upgrade"
require "./docs/j_modern_cli_and_tui/a_interactive_command_center"
require "./docs/j_modern_cli_and_tui/b_tui_hub_and_specialized_views"

alias Docs = ::Lapis::Docs

module Godot
  alias Docs = ::Lapis::Docs
end
{% end %}
