# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module A_GETTING_STARTED
      # # Installation & System Prerequisites
      #
      # Comprehensive walkthrough of installing all required tools to build, develop,
      # and run Lapis games on Windows, Linux, and macOS.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>System Capabilities</strong></td>
      #       <td><code>.topic_00_key_features</code></td>
      #       <td>Returns core capabilities and supported platforms for Lapis.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Prerequisites & Requirements</strong></td>
      #       <td><code>.topic_01_prerequisites</code></td>
      #       <td>Required compilers, runtimes, and engine versions before installing Lapis.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Windows Installation</strong></td>
      #       <td><code>.topic_02_windows_installation</code></td>
      #       <td>Step-by-step installation on Windows via installer, Scoop, or manual setup.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Linux & macOS Installation</strong></td>
      #       <td><code>.topic_03_linux_and_macos</code></td>
      #       <td>Installation procedures on Ubuntu/Debian, Fedora, Arch Linux, and macOS.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Verifying with Lapis Doctor</strong></td>
      #       <td><code>.topic_04_doctor_verification</code></td>
      #       <td>Running lapis doctor to validate all compilers, tools, and runtime dependencies.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Installation Pitfalls & FAQ</strong></td>
      #       <td><code>.topic_05_troubleshooting_faq</code></td>
      #       <td>Solutions to common installation, environment, and path issues.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Diagnostic Tool**: `tools/lapis/src/commands/doctor.cr`
      # - **Install Command**: `tools/lapis/src/commands/install.cr`
      # - **Engine Version Spec**: `godot-version.yml`
      # - **Related Submodule**: `Docs::A_GETTING_STARTED::B_COMPILATION`
      #
      module A_INSTALLATION
        # **System Capabilities**: Returns core capabilities and supported platforms for Lapis.
        #
        # #### Key Topics & Information
        #
        # - Full cross-platform support: Windows (x86_64), Linux (x86_64), macOS (arm64)
        # - Automated single-executable CLI toolchain (lapis) for all operations
        # - Zero-configuration GDExtension bridge with hot-reloading
        # - Comprehensive 11-point diagnostic environment checker (lapis doctor)
        #
        def self.topic_00_key_features : Nil; end

        # **Prerequisites & Requirements**: Required compilers, runtimes, and engine versions before installing Lapis.
        #
        # Before developing with Lapis, ensure the following core tools are installed on your workstation:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Component</th>
        #       <th>Recommended Version</th>
        #       <th>Purpose</th>
        #       <th>Download Source</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Crystal**</td>
        #       <td>1.20.0 to 1.21.0</td>
        #       <td>Primary compiled gameplay language</td>
        #       <td>[crystal-lang.org/install](https://crystal-lang.org/install/)</td>
        #     </tr>
        #     <tr>
        #       <td>**Godot Engine**</td>
        #       <td>4.8-dev6</td>
        #       <td>Target game engine executable</td>
        #       <td>[godotengine.org](https://godotengine.org)</td>
        #     </tr>
        #     <tr>
        #       <td>**C++ Compiler**</td>
        #       <td>MinGW-w64 g++ 15+ (Win) / clang (macOS)</td>
        #       <td>Compiles native GDExtension loader bridge</td>
        #       <td>Scoop / MSYS2 / Xcode</td>
        #     </tr>
        #     <tr>
        #       <td>**GNU Make**</td>
        #       <td>4.4+</td>
        #       <td>Workspace build & synchronization automation</td>
        #       <td>Scoop / apt / brew</td>
        #     </tr>
        #     <tr>
        #       <td>**Git**</td>
        #       <td>2.40+</td>
        #       <td>Version control & shard package resolution</td>
        #       <td>[git-scm.com](https://git-scm.com)</td>
        #     </tr>
        #     <tr>
        #       <td>**radare2**</td>
        #       <td>5.9.0+</td>
        #       <td>Native multi-threaded debugger & decompiler (pdc)</td>
        #       <td>Scoop / winget / apt / brew</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_01_prerequisites : Nil; end

        # **Windows Installation**: Step-by-step installation on Windows via installer, Scoop, or manual setup.
        #
        # On Windows, Lapis provides multiple installation avenues for rapid onboarding:
        #
        # #### Method 1: Official Windows Installer (Recommended)
        # Download and run `lapis-setup-windows-x86_64.exe` from the GitHub Releases page:
        # - Automatically stages `lapis.exe` into `%LOCALAPPDATA%\Programs\Lapis\bin`.
        # - Bundles the Crystalline LSP language server daemon and radare2 native debugger.
        # - Adds Lapis to the user `PATH` environment variable.
        # - Configures file associations and shell completions for PowerShell.
        #
        # #### Method 2: Scoop Package Manager
        # If you use Scoop for Windows development tooling:
        # ```powershell
        # scoop install crystal radare2 make git
        # # Run lapis global installer
        # .\bin\lapis.exe install
        # ```
        #
        # #### Method 3: Global Path Linking via Lapis CLI
        # If you compiled Lapis from source:
        # ```powershell
        # bin\lapis install --force
        # ```
        #
        def self.topic_02_windows_installation : Nil; end

        # **Linux & macOS Installation**: Installation procedures on Ubuntu/Debian, Fedora, Arch Linux, and macOS.
        #
        # #### Linux (Debian / Ubuntu)
        # Install prerequisites via `apt`:
        # ```bash
        # sudo apt update
        # sudo apt install -y build-essential curl git libyaml-dev libpcre2-dev libevent-dev
        # ```
        # Install pre-built `.deb` package:
        # ```bash
        # sudo dpkg -i lapis-0.0.132-amd64.deb
        # ```
        #
        # #### macOS (Apple Silicon / Intel)
        # Install prerequisites via Homebrew:
        # ```bash
        # brew install crystal make pcre2 bdw-gc libevent
        # ```
        # Install Lapis globally:
        # ```bash
        # ./bin/lapis install --prefix /usr/local
        # ```
        #
        def self.topic_03_linux_and_macos : Nil; end

        # **Verifying with Lapis Doctor**: Running lapis doctor to validate all compilers, tools, and runtime dependencies.
        #
        # After installation, run `lapis doctor` from any terminal to verify that your development environment is 100% operational:
        #
        # ```bash
        # lapis doctor
        # ```
        #
        # #### Expected Terminal Output:
        # ```text
        # [Doctor] Diagnosing Lapis development environment...
        # Diagnostic Results:
        #   [✓] Crystal Compiler: Crystal 1.21.0 (2026-07-16)
        #   [✓] Godot Engine: C:\Users\Dev\Documents\libgodot\godot.exe (v4.8.dev6.official.8898c2b3d)
        #   [✓] C++ Bridge Compiler: g++ (g++ (GCC) 15.2.0)
        #   [✓] Native Debugger (radare2): radare2 6.2.2 [native decompiler: pdc]
        #   [✓] GNU Make: Found at C:\Users\Dev\scoop\shims\make.exe
        #   [✓] Git Version Control: Found at C:\Program Files\Git\cmd\git.exe
        #   [✓] Crystal Shards Manager: Found at C:\Users\Dev\scoop\apps\crystal\current\shards.exe
        #   [✓] Crystalline LSP: C:\Users\Dev\AppData\Local\Programs\Lapis\bin\crystalline.exe (0.20.0)
        #   [✓] Inno Setup Compiler: Found at C:\Users\Dev\AppData\Local\Programs\Inno Setup 6\ISCC.exe
        #   [✓] Runtime Libraries: All 5 platform libraries verified in bin/
        #   [✓] Project Configuration: Godot project (libgodot) is fully configured for Crystal!
        #
        # [Lapis] Doctor diagnosis complete: 11/11 checks passed cleanly!
        # ```
        #
        def self.topic_04_doctor_verification : Nil; end

        # **Installation Pitfalls & FAQ**: Solutions to common installation, environment, and path issues.
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Running with Crystal < 1.20.0 will cause compilation errors due to missing ExecutionContext APIs.
        # - **Warning**: Missing g++ on Windows: ensure MinGW-w64 is in your system PATH (test with `g++ --version`).
        # - **Warning**: Godot binary mismatch: Lapis targets Godot 4.8-dev6; using 4.2 or 4.3 will trigger GDExtension ABI incompatibilities.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Can I use MSVC instead of MinGW-w64 on Windows?**
        #   A: Yes. Set CXX=cl in your environment or Makefile, though g++ is the default tested bridge compiler.
        #
        # - **Q: Where does lapis install place the executable?**
        #   A: On Windows: %LOCALAPPDATA%\Programs\Lapis\bin. On Linux/macOS: /usr/local/bin or ~/.local/bin.
        #
        def self.topic_05_troubleshooting_faq : Nil; end
      end
    end
  end
end
{% end %}
