# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module A_GETTING_STARTED
      # # Crystal Syntax Guide for Game Developers
      #
      # A fast-paced primer on the Crystal programming language specifically tailored for
      # developers coming from GDScript, Python, C#, or C++.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Why Crystal for Game Development?</strong></td>
      #       <td><code>.topic_00_crystal_strengths</code></td>
      #       <td>Key strengths: C-like execution speed, Ruby-like elegance, and compile-time safety.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Static Types & Nil Safety</strong></td>
      #       <td><code>.topic_01_types_and_nil_safety</code></td>
      #       <td>How Crystal combines static typing with type inference and compile-time nil checks.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Properties & Accessors</strong></td>
      #       <td><code>.topic_02_properties_and_accessors</code></td>
      #       <td>Crystal's property, getter, and setter macros vs GDScript variables.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Blocks, Yields & Closures</strong></td>
      #       <td><code>.topic_03_blocks_and_closures</code></td>
      #       <td>Functional iterators and code blocks in Crystal vs GDScript lambdas.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Official References & Coding Standards</strong></td>
      #       <td><code>.topic_04_official_resources</code></td>
      #       <td>Links to the official Crystal manual, standard library documentation, and style guides.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Official Reference**: [crystal-lang.org/reference](https://crystal-lang.org/reference/)
      # - **Standard Library API**: [crystal-lang.org/api](https://crystal-lang.org/api/)
      # - **Style Guide**: [crystal-lang.org/reference/conventions/coding_style.html](https://crystal-lang.org/reference/conventions/coding_style.html)
      #
      module D_CRYSTAL_BASICS_FOR_GODOT
        # **Why Crystal for Game Development?**: Key strengths: C-like execution speed, Ruby-like elegance, and compile-time safety.
        #
        # #### Key Topics & Information
        #
        # - Bare-metal performance: Compiles to native machine code via LLVM with zero VM overhead
        # - Guaranteed compile-time nil safety: No unexpected null reference crashes at runtime
        # - Elegant syntax: Clean, expressive syntax with powerful compile-time metaprogramming macros
        # - Fibers & CSP channels: Built-in lightweight concurrency apparatus
        #
        def self.topic_00_crystal_strengths : Nil; end

        # **Static Types & Nil Safety**: How Crystal combines static typing with type inference and compile-time nil checks.
        #
        # In GDScript or Python, variables can hold `null` at any time, leading to dreaded `Invalid get index on base Nil` errors.
        # In Crystal, non-nil types can **never** be nil:
        #
        # ```crystal
        # # 1. Non-nilable string - compiler guarantees it is always a String
        # name : String = "Hero"
        #
        # # 2. Nilable string - explicit union with Nil
        # target : String? = nil
        #
        # # 3. Compile-time check required before accessing nilable values:
        # if target
        #   Godot.print("Attacking target: #{target.upcase}") # Compiler knows target is not nil here!
        # else
        #   Godot.print("No target selected")
        # end
        #
        # # 4. Force unwrap (raises NilAssertionError if nil):
        # safe_target = target.not_nil!
        # ```
        #
        def self.topic_01_types_and_nil_safety : Nil; end

        # **Properties & Accessors**: Crystal's property, getter, and setter macros vs GDScript variables.
        #
        # In Crystal, instance variables are prefixed with `@` and private by default.
        # Crystal provides concise macros to generate getters and setters:
        #
        # ```crystal
        # class Weapon
        #   # Generates @name : String with getter and setter:
        #   property name : String
        #
        #   # Generates @damage : Int32 with getter only (read-only):
        #   getter damage : Int32
        #
        #   # Generates @secret_code with setter only (write-only):
        #   setter secret_code : String
        #
        #   def initialize(@name : String, @damage : Int32)
        #     @secret_code = "1234"
        #   end
        # end
        #
        # sword = Weapon.new("Excalibur", 50)
        # sword.name = "Excalibur +1" # OK: setter exists
        # puts sword.damage           # OK: getter exists
        # # sword.damage = 100        # Compile error: undefined method 'damage='
        # ```
        #
        def self.topic_02_properties_and_accessors : Nil; end

        # **Blocks, Yields & Closures**: Functional iterators and code blocks in Crystal vs GDScript lambdas.
        #
        # Blocks are one of Crystal's most powerful features for game systems:
        #
        # ```crystal
        # # Iterating over arrays with each:
        # enemies = ["Goblin", "Orc", "Dragon"]
        # enemies.each do |enemy|
        #   Godot.print("Spawned #{enemy}")
        # end
        #
        # # Transforming collections with map:
        # powers = [10, 20, 30]
        # boosted = powers.map { |p| p * 2 } # => [20, 40, 60]
        #
        # # Filtering with select:
        # alive_enemies = enemies.select { |e| e != "Goblin" }
        #
        # # Custom methods that take blocks:
        # def with_speed_boost(factor : Float32, &block)
        #   original_speed = @speed
        #   @speed *= factor
        #   yield # Runs the caller's code block
        #   @speed = original_speed
        # end
        # ```
        #
        def self.topic_03_blocks_and_closures : Nil; end

        # **Official References & Coding Standards**: Links to the official Crystal manual, standard library documentation, and style guides.
        #
        # To deepen your Crystal expertise, reference the authoritative documentation:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Resource</th>
        #       <th>Link</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><strong>Crystal Reference Manual</strong></td>
        #       <td><a href="https://crystal-lang.org/reference/">crystal-lang.org/reference</a></td>
        #       <td>Full language specification and macro syntax</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Standard Library API</strong></td>
        #       <td><a href="https://crystal-lang.org/api/">crystal-lang.org/api</a></td>
        #       <td>Built-in classes (Array, Hash, Math, Time, IO)</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Crystal Style Guide</strong></td>
        #       <td><a href="https://crystal-lang.org/reference/conventions/coding_style.html">Coding Style Guide</a></td>
        #       <td>Formatting, naming conventions, and best practices</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Crystal Forum &amp; Community</strong></td>
        #       <td><a href="https://forum.crystal-lang.org/">forum.crystal-lang.org</a></td>
        #       <td>Questions, community libraries, and ecosystem</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_04_official_resources : Nil; end
      end
    end
  end
end
{% end %}
