# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module J_MODERN_CLI_AND_TUI
      # # Interactive Terminal Command Center & Differential TUI
      #
      # Comprehensive architectural and operational guide to Lapis's modern, double-buffered
      # terminal user interface built with the Opal shard.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Command Center Overview</strong></td>
      #       <td><code>.topic_00_command_center_overview</code></td>
      #       <td>High-density telemetry dashboard, split-pane viewport, and real-time execution metrics.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Differential Cell Rendering</strong></td>
      #       <td><code>.topic_01_double_buffered_differential_rendering</code></td>
      #       <td>Zero-flicker double-buffered ANSI rendering powered by Opal::UI::DiffRenderer.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Multi-View Viewport Tabs</strong></td>
      #       <td><code>.topic_02_multi_view_tabs</code></td>
      #       <td>Tabbed navigation between Dashboard, Failures, Breakdown, and Live Telemetry.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Log Scrolling, Search & Clipboard Export</strong></td>
      #       <td><code>.topic_03_viewport_scrolling_and_search</code></td>
      #       <td>Real-time follow mode, substring pattern filtering, and OSC 52 system clipboard export.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Interactive Navigation & Keybindings</strong></td>
      #       <td><code>.topic_04_command_palette_and_keybindings</code></td>
      #       <td>Complete keyboard shortcuts reference for test inspection and modal navigation.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **CLI Runner**: `tools/lapis/src/commands/test.cr`
      # - **TUI Engine**: `tools/lapis/src/test_runner/tui.cr`
      # - **Diff Renderer**: `tools/lapis/lib/opal/src/ui/diff_renderer.cr`
      #
      module A_INTERACTIVE_COMMAND_CENTER
        # **Command Center Overview**: High-density telemetry dashboard, split-pane viewport, and real-time execution metrics.
        #
        # #### Features
        #
        # - Hero header displaying host OS, engine version, compiler version, active elapsed time, and heartbeat indicator.
        # - Split-pane layout: Left pane displays phased execution checklist; right pane displays rolling live logs.
        # - Real-time smooth progress bar with phase completion percentage and pass/fail counts.
        # - Automatic non-TTY fallback for CI/CD pipelines, background daemons, or when invoked with `--no-tui`.
        #
        def self.topic_00_command_center_overview : Nil; end

        # **Differential Cell Rendering**: Zero-flicker double-buffered ANSI rendering powered by Opal::UI::DiffRenderer.
        #
        # #### Mechanics
        #
        # 1. The TUI allocates a virtual screen buffer representing terminal grid cells `(char, style)`.
        # 2. Each update frame writes desired characters into the front buffer.
        # 3. `Opal::UI::DiffRenderer` compares front buffer cells against back buffer cells.
        # 4. Only modified cells emit ANSI cursor movement and color escape sequences to standard output.
        # 5. Completely eliminates screen tearing, flicker, and terminal lag during high-frequency log emission.
        #
        def self.topic_01_double_buffered_differential_rendering : Nil; end

        # **Multi-View Viewport Tabs**: Tabbed navigation between Dashboard, Failures, Breakdown, and Live Telemetry.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Tab Key</th>
        #       <th>View Name</th>
        #       <th>Purpose</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>1</code></td>
        #       <td><strong>Dashboard</strong></td>
        #       <td>Primary split-pane view displaying checklist phases and rolling stdout.</td>
        #     </tr>
        #     <tr>
        #       <td><code>2</code></td>
        #       <td><strong>Failures</strong></td>
        #       <td>Dedicated drill-down log view isolated strictly to failed test assertions.</td>
        #     </tr>
        #     <tr>
        #       <td><code>3</code></td>
        #       <td><strong>Breakdown</strong></td>
        #       <td>Tabular summary of test categories, durations, and quantitative metrics.</td>
        #     </tr>
        #     <tr>
        #       <td><code>4</code></td>
        #       <td><strong>Telemetry</strong></td>
        #       <td>Peak memory allocation, GC pause latency, and process thread counters.</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_02_multi_view_tabs : Nil; end

        # **Log Scrolling, Search & Clipboard Export**: Real-time follow mode, substring pattern filtering, and OSC 52 system clipboard export.
        #
        # #### Log Navigation Features
        #
        # - **Follow Mode (`f`)**: Automatically pins the viewport to the newest log entries. Pauses on manual scroll (`PageUp`/`PageDown`/`↑`/`↓`).
        # - **In-Log Search (`/`)**: Opens live prompt to highlight and cycle through matching log lines.
        # - **OSC 52 Clipboard Export (`c`)**: Copies selected log traces directly into the native OS system clipboard without external dependencies.
        #
        def self.topic_03_viewport_scrolling_and_search : Nil; end

        # **Interactive Navigation & Keybindings**: Complete keyboard shortcuts reference for test inspection and modal navigation.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Key</th>
        #       <th>Action</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>1</code> - <code>4</code></td>
        #       <td>Switch active viewport tab (Dashboard, Failures, Breakdown, Telemetry).</td>
        #     </tr>
        #     <tr>
        #       <td><code>↑</code> / <code>↓</code> or <code>j</code> / <code>k</code></td>
        #       <td>Navigate between test phases in checklist pane.</td>
        #     </tr>
        #     <tr>
        #       <td><code>PageUp</code> / <code>PageDown</code></td>
        #       <td>Scroll active logs viewport.</td>
        #     </tr>
        #     <tr>
        #       <td><code>f</code></td>
        #       <td>Toggle live autoscroll follow mode on or off.</td>
        #     </tr>
        #     <tr>
        #       <td><code>/</code></td>
        #       <td>Open substring search input.</td>
        #     </tr>
        #     <tr>
        #       <td><code>c</code></td>
        #       <td>Copy visible logs to clipboard via OSC 52.</td>
        #     </tr>
        #     <tr>
        #       <td><code>Enter</code> / <code>Space</code></td>
        #       <td>Open focused phase detail modal for comprehensive log inspection.</td>
        #     </tr>
        #     <tr>
        #       <td><code>?</code></td>
        #       <td>Toggle interactive help overlay.</td>
        #     </tr>
        #     <tr>
        #       <td><code>q</code> / <code>Ctrl+C</code></td>
        #       <td>Exit test runner cleanly.</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_04_command_palette_and_keybindings : Nil; end
      end
    end
  end
end
{% end %}
