# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module J_MODERN_CLI_AND_TUI
      # # Interactive TUI Hub & Domain Workspaces
      #
      # Comprehensive guide to the next-generation Lapis terminal user interface suite, including
      # the central navigation hub, interactive command palette, persistent editor supervisor,
      # context-aware packaging configurator, and dynamic radare2 crash forensics debugger.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Interactive Navigation Hub & Command Palette</strong></td>
      #       <td><code>.topic_00_interactive_cli_hub_and_palette</code></td>
      #       <td>Unified terminal navigation dashboard featuring live telemetry and floating command palette.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Project Scaffolding Wizard & Directory Selection</strong></td>
      #       <td><code>.topic_01_project_scaffolding_and_folder_dialog</code></td>
      #       <td>Interactive project generator with directory browser dialog for custom workspace paths.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Persistent Editor Supervisor & Real-Time Log Tailing</strong></td>
      #       <td><code>.topic_02_persistent_editor_supervisor</code></td>
      #       <td>Long-running Godot editor supervisor that monitors process status and streams engine stdout/stderr.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Context-Aware Packaging & Export Form</strong></td>
      #       <td><code>.topic_03_context_aware_packaging_form</code></td>
      #       <td>Multi-target export configurator with platform-specific compile-time macro filtering.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Radare2 Native Crash Forensics & Decompilation</strong></td>
      #       <td><code>.topic_04_radare2_crash_forensics_view</code></td>
      #       <td>Deep binary analysis workspace querying live r2 pipelines for real disassembly and decompilation.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Dynamic Benchmark Visualizer & Performance Analytics</strong></td>
      #       <td><code>.topic_05_dynamic_benchmark_visualizer</code></td>
      #       <td>Multi-dimensional performance analysis tool powered by Opal charts and live XML metrics parsing.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Runtime Performance Monitor & Process Telemetry</strong></td>
      #       <td><code>.topic_06_runtime_performance_monitor</code></td>
      #       <td>Real-time rolling FPS and RAM LineGraphs with graceful Ctrl+K process termination.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **CLI Hub**: `tools/lapis/src/tui/hub.cr`
      # - **Editor Launcher**: `tools/lapis/src/tui/editor_launcher.cr`
      # - **Package Form**: `tools/lapis/src/tui/package_form.cr`
      # - **Crash Forensics**: `tools/lapis/src/tui/debugger_view.cr`
      # - **Benchmark Visualizer**: `tools/lapis/src/tui/bench_viewer.cr`
      # - **Performance Monitor**: `tools/lapis/src/tui/run_monitor.cr`
      #
      module B_TUI_HUB_AND_SPECIALIZED_VIEWS
        # **Interactive Navigation Hub & Command Palette**: Unified terminal navigation dashboard featuring live telemetry and floating command palette.
        #
        # #### Architectural Invariants
        #
        # - The central terminal interface launched via `lapis cli` serves as a master dashboard for all developer workflows.
        # - Includes a persistent top header card showing host OS, architecture, Crystal compiler version, and Godot engine paths.
        # - A global command palette shortcut (<code>~</code>, <code>`</code>, or <code>Ctrl+P</code>) is registered across all subviews to allow instantaneous switching between tools without restarting the CLI.
        # - Built using double-buffered Opal virtual screen rendering with differential ANSI updates for silky smooth interaction.
        #
        def self.topic_00_interactive_cli_hub_and_palette : Nil; end

        # **Project Scaffolding Wizard & Directory Selection**: Interactive project generator with directory browser dialog for custom workspace paths.
        #
        # #### Mechanics & Directory Browsing
        #
        # - Accessible via `lapis new` (when in an interactive TTY) or through the hub menu.
        # - Integrates <code>Opal::UI::FileDialog</code> in <code>:open_dir</code> mode to let developers visually browse the filesystem and select destination directories.
        # - Configures project name, author name, target template (2D Starter, 3D Starter, or GDExtension Addon), and initializes Git repositories.
        # - Prevents scaffolding collisions by verifying directory vacancy and checking for existing <code>project.godot</code> files.
        #
        def self.topic_01_project_scaffolding_and_folder_dialog : Nil; end

        # **Persistent Editor Supervisor & Real-Time Log Tailing**: Long-running Godot editor supervisor that monitors process status and streams engine stdout/stderr.
        #
        # #### Process Lifecycle & Log Streaming
        #
        # - Launched via `lapis editor` or through the TUI hub.
        # - When executed in a directory without <code>project.godot</code>, prompts the user with an interactive directory picker instead of failing.
        # - Spawns the Godot editor asynchronously and keeps the TUI alive in the terminal.
        # - Uses non-blocking background fibers to continuously pump both <code>stdout</code> and <code>stderr</code> into a high-performance circular log buffer with scroll locking and keyword highlighting.
        # - Supports on-the-fly hot reloading (<code>R</code> key) and graceful process termination (<code>K</code> key).
        #
        def self.topic_02_persistent_editor_supervisor : Nil; end

        # **Context-Aware Packaging & Export Form**: Multi-target export configurator with platform-specific compile-time macro filtering.
        #
        # #### Target Invariants & Platform Awareness
        #
        # - Configures export targets including Playable Games, Portable Executables with embedded PCK footers, GDExtension Addon archives, and redistributable installers.
        # - Strictly macro-flags platform targets to ensure context-aware choices:
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Platform</th>
        #       <th>Macro Guard</th>
        #       <th>Available Specialized Target</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><strong>Windows</strong></td>
        #       <td><code>flag?(:windows)</code></td>
        #       <td>Windows Installer (<code>.exe</code> via NSIS / InnoSetup)</td>
        #     </tr>
        #     <tr>
        #       <td><strong>Linux</strong></td>
        #       <td><code>flag?(:linux)</code></td>
        #       <td>Debian Binary Package (<code>.deb</code> with desktop launcher)</td>
        #     </tr>
        #     <tr>
        #       <td><strong>macOS</strong></td>
        #       <td><code>flag?(:darwin)</code></td>
        #       <td>macOS Application Bundle Archive (<code>.app / .zip</code>)</td>
        #     </tr>
        #     <tr>
        #       <td><strong>All Platforms</strong></td>
        #       <td>Standard</td>
        #       <td>Playable Game, Portable Binary, Addon, Toolchain, Benchmarks</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_03_context_aware_packaging_form : Nil; end

        # **Radare2 Native Crash Forensics & Decompilation**: Deep binary analysis workspace querying live r2 pipelines for real disassembly and decompilation.
        #
        # #### Zero-Cheating Policy & Dynamic Queries
        #
        # - Automatically activates when a game or editor process crashes with access violation (<code>0xC0000005</code>) or abnormal signals.
        # - Strictly prohibits mock data, fake disassembly lines, or hardcoded registers.
        # - Dynamically queries <code>cradare2</code> for:
        #   1. <strong>Disassembly View</strong>: Real machine instructions fetched via <code>pdf</code>.
        #   2. <strong>Decompiler View</strong>: Pseudo-C decompilation extracted via <code>pdc</code>.
        #   3. <strong>CPU Registers</strong>: Live CPU register states parsed via <code>drj</code>.
        #   4. <strong>Memory Inspection</strong>: Raw binary byte visualization powered by <code>Opal::UI::HexViewer</code>.
        #   5. <strong>Demangled Call Stack</strong>: Crystal method backtraces retrieved via <code>client.crystal.demangled_backtrace</code>.
        #
        def self.topic_04_radare2_crash_forensics_view : Nil; end

        # **Dynamic Benchmark Visualizer & Performance Analytics**: Multi-dimensional performance analysis tool powered by Opal charts and live XML metrics parsing.
        #
        # #### Analytics & Charting
        #
        # - Parses real XML benchmark reports generated in <code>benchmarks/reports/*.xml</code> via <code>Commands::Benchmarks::XmlHandler</code>.
        # - Features an interactive file dialog to select past benchmark runs or triggers live benchmark execution directly from the TUI.
        # - Visualizes comparative metrics using rich Opal charts:
        #   - <code>Opal::UI::BarChart</code>: Crystal vs GDScript execution latency comparisons with speedup ratios.
        #   - <code>Opal::UI::PieChart</code>: Memory and processing category distribution.
        #   - <code>Opal::UI::LineGraph</code>: Historical trend across multiple successive benchmark runs.
        #
        def self.topic_05_dynamic_benchmark_visualizer : Nil; end

        # **Runtime Performance Monitor & Process Telemetry**: Real-time rolling FPS and RAM LineGraphs with graceful Ctrl+K process termination.
        #
        # #### Telemetry Monitoring
        #
        # - Launched via `lapis run --monitor` or `lapis bench --monitor`.
        # - Renders dual rolling line graphs showing frame rate (FPS) and memory allocation (MB) over the last 30 samples.
        # - Displays PID, uptime counter, peak RAM consumption, and current operational status.
        # - Provides instantaneous, graceful process termination via <code>Ctrl+K</code> or <code>K</code>, eliminating orphaned processes.
        #
        def self.topic_06_runtime_performance_monitor : Nil; end
      end
    end
  end
end
{% end %}
