# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\template-addon\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module MyAddon
  module Docs
    module A_GETTING_STARTED
      # # Addon Architecture & Extension Lifecycle
      #
      # Welcome to the Lapis Addon Template! This template provides a complete scaffold for authoring
      # redistributable Godot GDExtension plugins in Crystal. Your compiled addon can be installed into
      # any regular Godot project, providing custom nodes, editor tools, and gameplay systems without
      # requiring consumers to have Crystal installed.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>GDExtension Addon Architecture</strong></td>
      #       <td><code>.topic_01_addon_architecture</code></td>
      #       <td>How GDExtension loads your Crystal shared library via the C++ bridge.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>EditorPlugin Lifecycle</strong></td>
      #       <td><code>.topic_02_plugin_lifecycle</code></td>
      #       <td>Handling _enter_tree and _exit_tree in tool scripts.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/main.cr
      # - Makefile
      # - addons/my_addon/my_addon.gdextension
      #
      module A_OVERVIEW
        # **GDExtension Addon Architecture**: How GDExtension loads your Crystal shared library via the C++ bridge.
        #
        # The addon architecture consists of three core components:
        #
        # 1. **GDExtension Manifest (`.gdextension`)**: Instructs Godot which shared library to load for each platform (Windows DLL, Linux SO, macOS dylib).
        # 2. **Loader Bridge (`crystal_bridge.dll`)**: Bootstraps the Boehm GC and dispatches native engine callbacks into Crystal.
        # 3. **Compiled Addon Library (`game.dll`)**: Contains your registered Crystal nodes and `EditorPlugin` implementations.
        #
        # #### Working Examples
        #
        # ```
        # Godot Engine --> GDExtension Loader --> crystal_bridge.dll --> GC_init()
        #                                                                     |
        #                                                                     v
        #                                                              game.dll (Crystal Addon)
        #                                                                     |
        #                                                                     v
        #                                                          ClassDB Registration
        #                                                         (CrystalAddonBanner, etc.)
        # ```
        #
        def self.topic_01_addon_architecture : Nil; end

        # **EditorPlugin Lifecycle**: Handling _enter_tree and _exit_tree in tool scripts.
        #
        # An `EditorPlugin` runs directly inside the Godot Editor:
        #
        # ```crystal
        # @[Tool]
        # node CrystalAddonPlugin < EditorPlugin do
        #   def _enter_tree : Void
        #     Godot.print("[MyAddon] Plugin activated in Godot Editor!")
        #   end
        #
        #   def _exit_tree : Void
        #     Godot.print("[MyAddon] Plugin deactivated in Godot Editor.")
        #   end
        # end
        # ```
        #
        def self.topic_02_plugin_lifecycle : Nil; end
      end
    end
  end
end
{% end %}
