# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\template-addon\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module MyAddon
  module Docs
    module A_GETTING_STARTED
      # # Custom Nodes & Inspector Properties
      #
      # Custom nodes authored in Crystal are fully registered in Godot's `ClassDB`. They appear in the
      # Create New Node dialog, expose typed properties in the Godot Inspector, and emit signals that
      # can be wired to other nodes or GDScript handlers.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Creating Custom Control Nodes</strong></td>
      #       <td><code>.topic_01_control_nodes</code></td>
      #       <td>Declaring custom UI widgets with exported properties.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Packaging the Redistributable Addon</strong></td>
      #       <td><code>.topic_02_exporting_and_packaging</code></td>
      #       <td>Creating release archives for distribution on the Godot Asset Library or GitHub.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/main.cr
      #
      module B_CUSTOM_NODES
        # **Creating Custom Control Nodes**: Declaring custom UI widgets with exported properties.
        #
        # The template provides an example custom banner node (`CrystalAddonBanner < Control`):
        #
        # - `@[Export] property message : String`: Text displayed in the banner.
        # - `@[Export] property text_color : Color`: Tint color configured via Godot's color picker.
        # - `@[Export(range: 0.5..3.0)] property banner_scale : Float32`: Scale slider in the Inspector.
        # - `signal banner_clicked(message : String)`: Emitted when the banner receives click events.
        #
        # #### Working Examples
        #
        # ```crystal
        # node CrystalAddonBanner < Control do
        #   @[Export]
        #   property message : String = "Hello from Compiled Crystal Addon!"
        #
        #   @[Export]
        #   property text_color : Color = Color.new(0.3_f32, 0.9_f32, 1.0_f32, 1.0_f32)
        #
        #   signal banner_clicked(message : String)
        #
        #   def trigger_click : Void
        #     emit_banner_clicked(@message)
        #   end
        # end
        # ```
        #
        def self.topic_01_control_nodes : Nil; end

        # **Packaging the Redistributable Addon**: Creating release archives for distribution on the Godot Asset Library or GitHub.
        #
        # Use the `make package RELEASE=1` target to compile optimized binaries for your platform
        # and bundle the addon into a redistributable zip archive in `dist/`.
        #
        def self.topic_02_exporting_and_packaging : Nil; end
      end
    end
  end
end
{% end %}
