# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module D_CONCURRENCY_AND_FIBERS
      # # Fibers & Cooperative Signal Awaiting
      #
      # Comprehensive guide to running Crystal fibers in Godot's single-threaded scene loop,
      # cooperative yielding, and avoiding the top-level sleep deadlock trap.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>The Three Golden Fiber Invariants</strong></td>
      #       <td><code>.topic_00_fiber_rules</code></td>
      #       <td>Essential rules for writing asynchronous fiber code in LibGodot.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Yielding Execution in _process</strong></td>
      #       <td><code>.topic_01_cooperative_yielding</code></td>
      #       <td>Pumping spawned fibers cooperatively from the engine main thread.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>The Sleep Deadlock Hazard</strong></td>
      #       <td><code>.topic_02_the_sleep_deadlock_hazard</code></td>
      #       <td>Why sleep hangs in fibers and how to await timers safely.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Concurrency Safety**: `src/libgodot/extensions/scene_tree.cr`
      # - **Live Specs**: `spec/thread_safety_spec.cr`
      #
      module A_FIBERS_AND_COOPERATIVE_AWAIT
        # **The Three Golden Fiber Invariants**: Essential rules for writing asynchronous fiber code in LibGodot.
        #
        # #### Key Topics & Information
        #
        # - Rule 1: Godot owns the OS main loop; fibers must cooperatively yield via Fiber.yield
        # - Rule 2: NEVER call top-level sleep in a fiber; Godot does not pump LibEvent
        # - Rule 3: Use await(timer) or frame delta accumulators for time delays
        #
        def self.topic_00_fiber_rules : Nil; end

        # **Yielding Execution in _process**: Pumping spawned fibers cooperatively from the engine main thread.
        #
        # Because Godot controls the OS event loop, spawned fibers (`spawn do ... end`) will starve unless the main thread cooperatively yields:
        #
        # ```crystal
        # node GameManager < Node do
        #   def _ready : Void
        #     # Spawn a background gameplay fiber
        #     spawn do
        #       Godot.print("Dialog sequence started!")
        #       await(get_tree.create_timer(2.0))
        #       Godot.print("2 seconds elapsed non-blockingly!")
        #     end
        #   end
        #
        #   def _process(delta : Float64) : Void
        #     # Cooperatively yield time slice to pending fibers:
        #     Fiber.yield
        #   end
        # end
        # ```
        #
        def self.topic_01_cooperative_yielding : Nil; end

        # **The Sleep Deadlock Hazard**: Why sleep hangs in fibers and how to await timers safely.
        #
        # #### The Hazard:
        # In standard Crystal console programs, `sleep 2.seconds` registers a timer with Crystal's LibEvent / IOCP event loop. In LibGodot, Godot drives the main loop — not LibEvent! Calling top-level `sleep` suspends the fiber permanently, hanging that fiber indefinitely.
        #
        # #### The Safe Pattern:
        # Always use Godot's timer mechanism with `await`:
        # ```crystal
        # # SAFE: Suspends fiber until Godot's timer fires
        # await(get_tree.create_timer(1.5))
        # ```
        #
        def self.topic_02_the_sleep_deadlock_hazard : Nil; end
      end
    end
  end
end
{% end %}
