# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module D_CONCURRENCY_AND_FIBERS
      # # Main Thread Queue & Thread-Safe Dispatch
      #
      # Comprehensive guide to dispatching closures and methods from background OS worker threads
      # back onto the Godot Engine main thread.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Thread-Safe Notification Mechanisms</strong></td>
      #       <td><code>.topic_00_dispatch_methods</code></td>
      #       <td>Godot.on_main_thread closures vs Godot engine call_deferred.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Scheduling Work with Godot.on_main_thread</strong></td>
      #       <td><code>.topic_01_on_main_thread</code></td>
      #       <td>Enqueueing Crystal closures from background workers to mutate nodes safely.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Thread Safety Engine**: `src/libgodot/thread_safety.cr`
      # - **Macros**: `src/libgodot/macros.cr`
      #
      module C_MAIN_THREAD_DISPATCH
        # **Thread-Safe Notification Mechanisms**: Godot.on_main_thread closures vs Godot engine call_deferred.
        #
        # #### Key Topics & Information
        #
        # - Godot.on_main_thread { ... }: Crystal closure queue flushed every frame in _process
        # - node.call_deferred(method, *args): Godot engine MessageQueue dispatch
        # - ThreadSafety.assert_main_thread!: Defensive guard against illegal background mutation
        #
        def self.topic_00_dispatch_methods : Nil; end

        # **Scheduling Work with Godoton_main_thread**: Enqueueing Crystal closures from background workers to mutate nodes safely.
        #
        # When a background worker thread needs to create nodes or update the SceneTree:
        #
        # ```crystal
        # Thread.new do
        #   heavy_procedural_texture = generate_terrain_noise
        #
        #   # Safely hand off to main thread:
        #   Godot.on_main_thread do
        #     sprite = Godot.create(Godot::Sprite2D)
        #     sprite.texture = heavy_procedural_texture
        #     add_child(sprite) # SAFE: Dispatched on the engine main thread!
        #   end
        # end
        # ```
        #
        # #### How It Works:
        # The queue is thread-safe and guarded by a `::Thread::Mutex`. On every frame during `_process` and `_physics_process`, `Godot::ThreadSafety.flush_main_thread_queue!` drains the queue and executes the closures on the main thread.
        #
        def self.topic_01_on_main_thread : Nil; end
      end
    end
  end
end
{% end %}
