# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Declarative Node DSL & Lifecycle
      #
      # Comprehensive guide to authoring gameplay entities using Lapis's declarative Node DSL,
      # ClassDB registration, and engine lifecycle virtual methods.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Core DSL Features</strong></td>
      #       <td><code>.topic_00_dsl_features</code></td>
      #       <td>Declarative class registration, export properties, typed signals, and in-editor tool execution.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Node Declaration Syntax</strong></td>
      #       <td><code>.topic_01_node_declaration</code></td>
      #       <td>Declaring custom nodes inheriting from 2D, 3D, UI, or Server nodes.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Engine Lifecycle Virtual Methods</strong></td>
      #       <td><code>.topic_02_lifecycle_methods</code></td>
      #       <td>Virtual methods invoked by the Godot scene tree during execution.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>In-Editor Tool Scripts (@[Tool])</strong></td>
      #       <td><code>.topic_03_tool_scripts</code></td>
      #       <td>Executing Crystal code live inside the Godot Editor viewport and scene dock.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Ergonomic Node Declarations & Groups</strong></td>
      #       <td><code>.topic_04_node_helpers</code></td>
      #       <td>Convenient macros for groups, cached node references, and unique scene access.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Macro DSL**: `src/libgodot/macros.cr`
      # - **Live Specs**: `spec/suites/test_node_dsl.cr`
      # - **Showcase**: `examples/basic_demo/src/main.cr`
      #
      module A_NODE_DSL
        # **Core DSL Features**: Declarative class registration, export properties, typed signals, and in-editor tool execution.
        #
        # #### Key Topics & Information
        #
        # - Declarative syntax: node ClassName < ParentNode do ... end
        # - Automatic ClassDB engine registration
        # - Virtual method overrides: _ready, _process, _physics_process, _enter_tree, _exit_tree
        # - In-editor live execution via @[Tool] annotation
        #
        def self.topic_00_dsl_features : Nil; end

        # **Node Declaration Syntax**: Declaring custom nodes inheriting from 2D, 3D, UI, or Server nodes.
        #
        # Declare a custom Godot node using the `node` macro:
        #
        # ```crystal
        # require "libgodot"
        #
        # node Enemy < CharacterBody2D do
        #   @[Export]
        #   property max_health : Int32 = 100
        #
        #   def _ready : Void
        #     Godot.print("Enemy #{name} ready!")
        #   end
        # end
        # ```
        #
        # #### Supported Parent Classes:
        # You can inherit from any registered Godot engine node:
        # - **2D Nodes**: `Node2D`, `Sprite2D`, `CharacterBody2D`, `Area2D`, `RigidBody2D`
        # - **3D Nodes**: `Node3D`, `MeshInstance3D`, `CharacterBody3D`, `Camera3D`
        # - **UI Controls**: `Control`, `Label`, `Button`, `Panel`, `ProgressBar`
        # - **Servers**: Direct RID manipulation with `RenderingServer`, `PhysicsServer2D`
        #
        def self.topic_01_node_declaration : Nil; end

        # **Engine Lifecycle Virtual Methods**: Virtual methods invoked by the Godot scene tree during execution.
        #
        # Godot dispatches lifecycle callbacks to custom nodes:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Virtual Method</th>
        #       <th>Invocation Timing</th>
        #       <th>Typical Use Case</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>_enter_tree : Void</code></td>
        #       <td>When node enters active scene tree</td>
        #       <td>Subscribing to signals, global lookups</td>
        #     </tr>
        #     <tr>
        #       <td><code>_ready : Void</code></td>
        #       <td>When node and all children enter tree</td>
        #       <td>Initialization, setting initial positions</td>
        #     </tr>
        #     <tr>
        #       <td><code>_process(delta : Float64) : Void</code></td>
        #       <td>Every visual render frame</td>
        #       <td>Smooth visuals, UI updates, animations</td>
        #     </tr>
        #     <tr>
        #       <td><code>_physics_process(delta : Float64) : Void</code></td>
        #       <td>Fixed-rate physics step (60 Hz)</td>
        #       <td>Movement, raycasts, collision calculations</td>
        #     </tr>
        #     <tr>
        #       <td><code>_exit_tree : Void</code></td>
        #       <td>When node leaves active scene tree</td>
        #       <td>Cleanup, unregistering listeners</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_02_lifecycle_methods : Nil; end

        # **In-Editor Tool Scripts (@[Tool])**: Executing Crystal code live inside the Godot Editor viewport and scene dock.
        #
        # Annotate a class with `@[Tool]` to have it execute inside the Godot Editor:
        #
        # ```crystal
        # @[Tool]
        # node LevelGenerator < Node2D do
        #   @[ExportToolButton("Generate Maze")]
        #   property generate_button : ToolButton do
        #     generate_level!
        #   end
        #
        #   def generate_level! : Void
        #     Godot.print("Procedural generation running in Godot Editor!")
        #   end
        # end
        # ```
        #
        # When selected in the editor, clicking the inspector tool button executes the Crystal code live in the viewport!
        #
        def self.topic_03_tool_scripts : Nil; end

        # **Ergonomic Node Declarations & Groups**: Convenient macros for groups, cached node references, and unique scene access.
        #
        # Lapis provides built-in macros for declarative scene setup directly inside the `node` block:
        #
        # ```crystal
        # node Player < CharacterBody2D do
        #   # Declarative group membership
        #   group "players", "damageable"
        #
        #   # Cached node references (typed and nilable variants)
        #   onready sprite : Sprite2D
        #   onready? particle_fx : CPUParticles2D
        #
        #   # Scene Unique Node access (%UniqueNodeName)
        #   unique_node health_bar : ProgressBar
        #   unique_node? quest_tracker : Control
        # end
        # ```
        #
        def self.topic_04_node_helpers : Nil; end
      end
    end
  end
end
{% end %}
