# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Declarative Node DSL & Lifecycle
      #
      # Comprehensive guide to authoring gameplay entities using Lapis's declarative Node DSL,
      # ClassDB registration, and engine lifecycle virtual methods.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Core DSL Features</strong></td>
      #       <td><code>.topic_00_dsl_features</code></td>
      #       <td>Declarative class registration, export properties, typed signals, and in-editor tool execution.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Node Declaration Syntax</strong></td>
      #       <td><code>.topic_01_node_declaration</code></td>
      #       <td>Declaring custom nodes inheriting from 2D, 3D, UI, or Server nodes.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Engine Lifecycle Virtual Methods</strong></td>
      #       <td><code>.topic_02_lifecycle_methods</code></td>
      #       <td>Virtual methods invoked by the Godot scene tree during execution.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>In-Editor Tool Scripts (@[Tool])</strong></td>
      #       <td><code>.topic_03_tool_scripts</code></td>
      #       <td>Executing Crystal code live inside the Godot Editor viewport and scene dock.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Ergonomic Node Declarations & Groups</strong></td>
      #       <td><code>.topic_04_node_helpers</code></td>
      #       <td>Convenient macros for groups, cached node references, and unique scene access.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Context-Aware Node Reopening (Define vs. Monkeypatch Mode)</strong></td>
      #       <td><code>.topic_05_context_aware_node_reopening</code></td>
      #       <td>Modularizing Godot node definitions across multiple files without inheritance conflicts.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Traditional GodotClass Annotation Syntax</strong></td>
      #       <td><code>.topic_06_traditional_godot_class_syntax</code></td>
      #       <td>Authoring native Godot nodes using standard Crystal class syntax and the @[GodotClass] annotation.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Pure Crystal Domain Models & Stack-Allocated Structs</strong></td>
      #       <td><code>.topic_07_pure_crystal_domain_models</code></td>
      #       <td>Decoupling game logic into zero-allocation stack structs for 30ms headless testing and peak cache efficiency.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Macro DSL**: `src/libgodot/macros.cr`
      # - **Live Specs**: `spec/suites/test_node_dsl.cr`
      # - **Showcase**: `examples/basic_demo/src/main.cr`
      #
      module A_NODE_DSL
        # **Core DSL Features**: Declarative class registration, export properties, typed signals, and in-editor tool execution.
        #
        # #### Key Topics & Information
        #
        # - Declarative syntax: node ClassName < ParentNode do ... end
        # - Context-aware node reopening across files without inheritance conflict
        # - Traditional class syntax via @[GodotClass] annotation
        # - Pure Crystal domain models with zero GC stack-allocated structs
        # - Automatic ClassDB engine registration
        # - Virtual method overrides: _ready, _process, _physics_process, _enter_tree, _exit_tree
        # - In-editor live execution via @[Tool] annotation
        #
        def self.topic_00_dsl_features : Nil; end

        # **Node Declaration Syntax**: Declaring custom nodes inheriting from 2D, 3D, UI, or Server nodes.
        #
        # Declare a custom Godot node using the `node` macro:
        #
        # ```crystal
        # require "libgodot"
        #
        # node Enemy < CharacterBody2D do
        #   @[Export]
        #   property max_health : Int32 = 100
        #
        #   def _ready : Void
        #     Godot.print("Enemy #{name} ready!")
        #   end
        # end
        # ```
        #
        # #### Supported Parent Classes:
        # You can inherit from any registered Godot engine node:
        # - **2D Nodes**: `Node2D`, `Sprite2D`, `CharacterBody2D`, `Area2D`, `RigidBody2D`
        # - **3D Nodes**: `Node3D`, `MeshInstance3D`, `CharacterBody3D`, `Camera3D`
        # - **UI Controls**: `Control`, `Label`, `Button`, `Panel`, `ProgressBar`
        # - **Servers**: Direct RID manipulation with `RenderingServer`, `PhysicsServer2D`
        #
        def self.topic_01_node_declaration : Nil; end

        # **Engine Lifecycle Virtual Methods**: Virtual methods invoked by the Godot scene tree during execution.
        #
        # Godot dispatches lifecycle callbacks to custom nodes:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Virtual Method</th>
        #       <th>Invocation Timing</th>
        #       <th>Typical Use Case</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>_enter_tree : Void</code></td>
        #       <td>When node enters active scene tree</td>
        #       <td>Subscribing to signals, global lookups</td>
        #     </tr>
        #     <tr>
        #       <td><code>_ready : Void</code></td>
        #       <td>When node and all children enter tree</td>
        #       <td>Initialization, setting initial positions</td>
        #     </tr>
        #     <tr>
        #       <td><code>_process(delta : Float64) : Void</code></td>
        #       <td>Every visual render frame</td>
        #       <td>Smooth visuals, UI updates, animations</td>
        #     </tr>
        #     <tr>
        #       <td><code>_physics_process(delta : Float64) : Void</code></td>
        #       <td>Fixed-rate physics step (60 Hz)</td>
        #       <td>Movement, raycasts, collision calculations</td>
        #     </tr>
        #     <tr>
        #       <td><code>_exit_tree : Void</code></td>
        #       <td>When node leaves active scene tree</td>
        #       <td>Cleanup, unregistering listeners</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_02_lifecycle_methods : Nil; end

        # **In-Editor Tool Scripts (@[Tool])**: Executing Crystal code live inside the Godot Editor viewport and scene dock.
        #
        # Annotate a class with `@[Tool]` to have it execute inside the Godot Editor:
        #
        # ```crystal
        # @[Tool]
        # node LevelGenerator < Node2D do
        #   @[ExportToolButton("Generate Maze")]
        #   property generate_button : ToolButton do
        #     generate_level!
        #   end
        #
        #   def generate_level! : Void
        #     Godot.print("Procedural generation running in Godot Editor!")
        #   end
        # end
        # ```
        #
        # When selected in the editor, clicking the inspector tool button executes the Crystal code live in the viewport!
        #
        def self.topic_03_tool_scripts : Nil; end

        # **Ergonomic Node Declarations & Groups**: Convenient macros for groups, cached node references, and unique scene access.
        #
        # Lapis provides built-in macros for declarative scene setup directly inside the `node` block:
        #
        # ```crystal
        # node Player < CharacterBody2D do
        #   # Declarative group membership
        #   group "players", "damageable"
        #
        #   # Eager onready property initialized during _ready via unary ~:
        #   onready sprite : Sprite2D = ~"Sprite2D"
        #   onready health_bar : ProgressBar = ~"%HealthBar"
        #   onready anim = ~"AnimationPlayer".as(AnimationPlayer)
        #
        #   # Lazy-cached node accessors (resolved on first access with dead-pointer safety):
        #   onready camera, Camera2D, "Pivot/Camera2D"
        #   onready? particle_fx, CPUParticles2D
        #
        #   # Scene Unique Node access (%UniqueNodeName)
        #   unique_node hud, CanvasLayer, "PlayerHUD"
        #   unique_node? quest_tracker, Control
        # end
        # ```
        #
        def self.topic_04_node_helpers : Nil; end

        # **Context-Aware Node Reopening (Define vs Monkeypatch Mode)**: Modularizing Godot node definitions across multiple files without inheritance conflicts.
        #
        # Lapis features a context-aware `node` macro that distinguishes between the initial class definition and subsequent class reopenings (monkeypatching).
        #
        # In standard Crystal, declaring `class Player < CharacterBody2D` a second time triggers a compile-time superclass mismatch or redefinition error. Lapis inspects class resolution at compile time:
        # - **Initial Definition**: `node Player < CharacterBody2D` creates the class, registers it in `ClassDB`, binds initial exported properties and lifecycle methods.
        # - **Reopening (Monkeypatch)**: Subsequent declarations (`node Player do ... end`) automatically open the class in monkeypatch mode without repeating `< SuperClass`.
        #
        # All exported properties, signals, RPC definitions, and virtual methods from reopened blocks are dynamically merged into a single unified `ClassDB` table:
        #
        # ```crystal
        # # File: src/entities/player.cr
        # node Player < CharacterBody2D do
        #   @[Export]
        #   property speed : Float32 = 250.0_f32
        #
        #   def _physics_process(delta : Float64) : Void
        #     # Movement logic
        #   end
        # end
        #
        # # File: src/entities/player_combat.cr
        # node Player do
        #   signal health_changed(current : Int32, max : Int32)
        #
        #   @[Export]
        #   property attack_power : Int32 = 25
        #
        #   def take_damage(amount : Int32) : Void
        #     # Combat resolution
        #   end
        # end
        # ```
        #
        # Dispatch methods (`_godot_call_virtual`, `_godot_set_property`, `_godot_get_property`) seamlessly chain to `previous_def`, allowing modular code splitting across feature directories without runtime overhead.
        #
        def self.topic_05_context_aware_node_reopening : Nil; end

        # **Traditional GodotClass Annotation Syntax**: Authoring native Godot nodes using standard Crystal class syntax and the @[GodotClass] annotation.
        #
        # Developers who prefer traditional object-oriented Crystal class syntax over declarative macro blocks can annotate standard classes with `@[GodotClass]`:
        #
        # ```crystal
        # require "libgodot"
        #
        # @[GodotClass]
        # class Player < Godot::CharacterBody2D
        #   @[Export]
        #   property speed : Float32 = 300.0_f32
        #
        #   @[Export]
        #   property max_health : Int32 = 100
        #
        #   def _ready : Void
        #     Godot.print("Player #{name} initialized via @[GodotClass]!")
        #   end
        #
        #   def _physics_process(delta : Float64) : Void
        #     # Standard physics movement
        #   end
        # end
        # ```
        #
        # #### Automated ClassDB Synthesis:
        # When a class inherits from any `Godot::Object` subclass and carries `@[GodotClass]`:
        # 1. **ClassDB Registration**: Automatically generates entry with proper parent class name (`CharacterBody2D`).
        # 2. **Property Reflection**: Gathers all `@[Export]` properties and registers typed `PropertyInfo` entries into the Godot Inspector.
        # 3. **Virtual Dispatch**: Automatically wires `_ready`, `_process`, `_physics_process`, and input methods to engine ptrcalls.
        # 4. **Zero Macro Boilerplate**: Requires no `node do ... end` wrapper blocks, matching standard Crystal class design.
        #
        def self.topic_06_traditional_godot_class_syntax : Nil; end

        # **Pure Crystal Domain Models & Stack-Allocated Structs**: Decoupling game logic into zero-allocation stack structs for 30ms headless testing and peak cache efficiency.
        #
        # While Godot nodes are excellent for spatial hierarchies and rendering, writing all gameplay logic directly inside engine nodes introduces native wrapper overhead, garbage collection pressure, and slow test feedback loops.
        #
        # Lapis enables a high-performance **Domain-Driven Design (DDD)** pattern using pure Crystal stack-allocated structs:
        #
        # ```crystal
        # # Zero GC allocation - lives directly in parent memory
        # struct CombatStats
        #   property health : Int32
        #   property max_health : Int32
        #   property defense : Int32
        #   property attack_power : Int32
        #
        #   def initialize(@max_health : Int32, @defense : Int32, @attack_power : Int32)
        #     @health = @max_health
        #   end
        #
        #   def alive? : Bool
        #     @health > 0
        #   end
        #
        #   # Pure deterministic calculation - zero engine dependencies
        #   def apply_incoming_damage(raw_damage : Int32) : Int32
        #     mitigated = Math.max(1, raw_damage - @defense)
        #     @health = Math.max(0, @health - mitigated)
        #     mitigated
        #   end
        # end
        # ```
        #
        # #### Clean Composition inside a Godot Node:
        # The Godot node acts strictly as a visual renderer and spatial bridge:
        #
        # ```crystal
        # node Player < CharacterBody2D do
        #   # Inlined directly in memory - no separate heap pointer
        #   @stats = CombatStats.new(max_health: 100, defense: 15, attack_power: 25)
        #
        #   def take_hit(damage : Int32) : Void
        #     mitigated = @stats.apply_incoming_damage(damage)
        #     Godot.print("Player took #{mitigated} damage! Remaining: #{@stats.health}")
        #     queue_free unless @stats.alive?
        #   end
        # end
        # ```
        #
        # #### High-Velocity Test-Driven Development (TDD):
        # Because `CombatStats` and other domain models have no dependency on Godot's SceneTree, developers can write comprehensive headless Crystal specs:
        #
        # ```crystal
        # # spec/domain/combat_stats_spec.cr
        # require "spec"
        # require "../../src/domain/combat_stats"
        #
        # describe CombatStats do
        #   it "correctly mitigates damage by defense rating" do
        #     stats = CombatStats.new(max_health: 100, defense: 10, attack_power: 20)
        #     actual_dmg = stats.apply_incoming_damage(35)
        #     actual_dmg.should eq(25)
        #     stats.health.should eq(75)
        #     stats.alive?.should be_true
        #   end
        # end
        # ```
        #
        # Running `crystal spec spec/domain/` executes hundreds of unit tests in **30 milliseconds (0.03s)**, without booting Godot, creating OS windows, or waiting for scene tree initialization!
        #
        def self.topic_07_pure_crystal_domain_models : Nil; end
      end
    end
  end
end
{% end %}
