# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Export System & Inspector Integration
      #
      # Comprehensive guide to exposing Crystal properties to the Godot Editor Inspector using
      # the `@Export` annotation family.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Supported Export Annotations</strong></td>
      #       <td><code>.topic_00_export_types</code></td>
      #       <td>Listing of ranges, enums, flags, files, directories, and buttons.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Numeric Ranges & Sliders</strong></td>
      #       <td><code>.topic_01_numeric_ranges</code></td>
      #       <td>Configuring slider ranges, increments, and easing curves.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Enums & Bitmask Flags</strong></td>
      #       <td><code>.topic_02_enums_and_flags</code></td>
      #       <td>Exposing dropdown menus and multi-select checkboxes.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>File & Directory Pickers</strong></td>
      #       <td><code>.topic_03_file_and_asset_pickers</code></td>
      #       <td>Exposing resource path selectors with filter extensions.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Export Macros**: `src/libgodot/macros/export.cr`
      # - **Live Specs**: `spec/suites/test_exports.cr`
      #
      module B_EXPORTS_AND_INSPECTOR
        # **Supported Export Annotations**: Listing of ranges, enums, flags, files, directories, and buttons.
        #
        # #### Key Topics & Information
        #
        # - @[Export]: Standard property export for numbers, strings, colors, vectors
        # - @[Export(range: min..max, step: n)]: Number slider or range constraint
        # - @[Export(enum: Type)]: Dropdown enum selector
        # - @[Export(flags: Type)]: Bitmask flag checkbox list
        # - @[ExportFile] / @[ExportDir]: Interactive file and directory pickers
        # - @[ExportToolButton]: Interactive clickable button in editor inspector
        #
        def self.topic_00_export_types : Nil; end

        # **Numeric Ranges & Sliders**: Configuring slider ranges, increments, and easing curves.
        #
        # ```crystal
        # node PlayerStats < Node do
        #   # Integer range slider from 1 to 100 with step 1
        #   @[Export(range: 1..100, step: 1)]
        #   property health : Int32 = 100
        #
        #   # Float slider from 0.0 to 10.0 with step 0.1
        #   @[Export(range: 0.0_f32..10.0_f32, step: 0.1_f32)]
        #   property move_multiplier : Float32 = 1.0_f32
        #
        #   # Exponential easing curve slider for audio/visual ramps
        #   @[ExportExpEasing]
        #   property falloff : Float32 = 0.5_f32
        # end
        # ```
        #
        def self.topic_01_numeric_ranges : Nil; end

        # **Enums & Bitmask Flags**: Exposing dropdown menus and multi-select checkboxes.
        #
        # ```crystal
        # enum WeaponType
        #   Sword
        #   Bow
        #   Staff
        # end
        #
        # @[Flags]
        # enum CollisionLayers
        #   World  = 1
        #   Player = 2
        #   Enemy  = 4
        # end
        #
        # node CombatEntity < Node do
        #   # Renders as a clean dropdown in Godot Inspector
        #   @[ExportEnum]
        #   property weapon : WeaponType = WeaponType::Sword
        #
        #   # Renders as multi-select bitmask flags
        #   @[ExportFlags]
        #   property collision_mask : CollisionLayers = CollisionLayers::World | CollisionLayers::Player
        # end
        # ```
        #
        def self.topic_02_enums_and_flags : Nil; end

        # **File & Directory Pickers**: Exposing resource path selectors with filter extensions.
        #
        # ```crystal
        # node SoundPlayer < AudioStreamPlayer do
        #   # File selector filtered to audio formats
        #   @[ExportFile(filter: "*.wav,*.ogg,*.mp3")]
        #   property audio_file : String = ""
        #
        #   # Directory selector
        #   @[ExportDir]
        #   property asset_directory : String = "res://assets"
        # end
        # ```
        #
        def self.topic_03_file_and_asset_pickers : Nil; end
      end
    end
  end
end
{% end %}
