# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Signals & Event-Driven Architecture
      #
      # Comprehensive guide to Godot's reactive event system in Crystal, covering declaration,
      # emission, inter-language connections, and cooperative signal awaiting with `await`.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Signal Capabilities</strong></td>
      #       <td><code>.topic_00_signal_features</code></td>
      #       <td>Type-safe signal emission, reflection, and cooperative fiber suspension.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Declaring & Emitting Signals</strong></td>
      #       <td><code>.topic_01_signal_declaration</code></td>
      #       <td>Declaring signals and calling generated type-safe emit methods.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Connecting Signals in Crystal & GDScript</strong></td>
      #       <td><code>.topic_02_connecting_signals</code></td>
      #       <td>Subscribing to signals across Crystal nodes and GDScript scripts.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Cooperative Signal Awaiting (await)</strong></td>
      #       <td><code>.topic_03_awaiting_signals</code></td>
      #       <td>Suspending gameplay fibers non-blockingly until a signal arrives or times out.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Signal Macros**: `src/libgodot/macros/signals.cr`
      # - **Live Specs**: `spec/suites/test_signals.cr`
      #
      module C_SIGNALS_AND_EVENTS
        # **Signal Capabilities**: Type-safe signal emission, reflection, and cooperative fiber suspension.
        #
        # #### Key Topics & Information
        #
        # - Declarative syntax: signal name(arg1 : Type1, arg2 : Type2)
        # - Synthesized type-safe emission helpers: emit_name(arg1, arg2)
        # - First-class signal awaiting: await(node.signal_name, timeout_sec: 5.0)
        # - Full ClassDB reflection for Godot connections dialog and GDScript interop
        #
        def self.topic_00_signal_features : Nil; end

        # **Declaring & Emitting Signals**: Declaring signals and calling generated type-safe emit methods.
        #
        # Declare signals using the `signal` macro inside any `node`:
        #
        # ```crystal
        # node HealthSystem < Node do
        #   # Signal with typed parameters
        #   signal health_changed(current : Int32, max : Int32)
        #
        #   # Parameterless signal
        #   signal died
        #
        #   property current_hp : Int32 = 100
        #   property max_hp : Int32 = 100
        #
        #   def take_damage(amount : Int32) : Void
        #     @current_hp = (@current_hp - amount).clamp(0, @max_hp)
        #
        #     # Call ergonomic emit helper (or synthesized emit_<name>):
        #     emit(health_changed, @current_hp, @max_hp)
        #
        #     if @current_hp <= 0
        #       emit(died)
        #     end
        #   end
        # end
        # ```
        #
        def self.topic_01_signal_declaration : Nil; end

        # **Connecting Signals in Crystal & GDScript**: Subscribing to signals across Crystal nodes and GDScript scripts.
        #
        # #### Connecting in Crystal:
        # ```crystal
        # # Connect with a block directly on first-class bound signals:
        # player.died.connect do
        #   Godot.print("Player has perished!")
        # end
        #
        # # Typed signal callbacks receive arguments:
        # player.health_changed.connect do |args|
        #   Godot.print("Health updated: #{args[0]} / #{args[1]}")
        # end
        # ```
        #
        # #### Connecting in GDScript:
        # ```gdscript
        # func _ready():
        #     var player = $Player
        #     player.health_changed.connect(_on_health_changed)
        #
        # func _on_health_changed(current: int, max_hp: int):
        #     print("Player health: ", current, "/", max_hp)
        # ```
        #
        def self.topic_02_connecting_signals : Nil; end

        # **Cooperative Signal Awaiting (await)**: Suspending gameplay fibers non-blockingly until a signal arrives or times out.
        #
        # Lapis supports first-class cooperative signal awaiting without blocking the engine main loop:
        #
        # ```crystal
        # # Suspend until enemy dies:
        # await(enemy.died)
        #
        # # Await with timeout (raises TimeoutError or returns nil):
        # await(boss.defeated, timeout_sec: 10.0)
        #
        # # Awaiting a timer:
        # timer = get_tree.create_timer(2.0)
        # await(timer.timeout)
        # ```
        #
        def self.topic_03_awaiting_signals : Nil; end
      end
    end
  end
end
{% end %}
