# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Low-Latency Input & Controls
      #
      # Comprehensive guide to authoring ultra-responsive controls, FPS camera look,
      # sub-frame motion sampling, and zero-allocation input polling.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Input Processing Paradigms</strong></td>
      #       <td><code>.topic_00_input_methods</code></td>
      #       <td>Event-driven (_unhandled_input) vs frame polling (Input singleton).</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Continuous Input Polling</strong></td>
      #       <td><code>.topic_01_polling_input</code></td>
      #       <td>Reading keyboard, mouse, and gamepad analog axes without heap allocations.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Sub-Frame FPS Mouse Look</strong></td>
      #       <td><code>.topic_02_mouse_look</code></td>
      #       <td>Smooth 3D first-person camera rotation with InputEventMouseMotion.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Input Guide**: `src/libgodot/extensions/input.cr`
      # - **Live Specs**: `spec/suites/test_input.cr`
      #
      module D_LOW_LATENCY_INPUT
        # **Input Processing Paradigms**: Event-driven (_unhandled_input) vs frame polling (Input singleton).
        #
        # #### Key Topics & Information
        #
        # - Event-driven: _unhandled_input(event : InputEvent) for discrete actions & mouse motion
        # - Polling: Input.action_pressed? and Input.action_just_pressed? for responsive movement
        # - Axis queries: Input.vector and Input.axis for 2D/3D direction
        # - Sub-frame mouse look with event accumulation disabled
        #
        def self.topic_00_input_methods : Nil; end

        # **Continuous Input Polling**: Reading keyboard, mouse, and gamepad analog axes without heap allocations.
        #
        # Inside `_physics_process(delta)`:
        #
        # ```crystal
        # def _physics_process(delta : Float64) : Void
        #   # 1. 2D Movement vector with automatic deadzone normalization
        #   move_vector = Input.vector("move_left", "move_right", "move_up", "move_down")
        #
        #   # 2. Discrete action checks
        #   if Input.action_just_pressed?("jump") && on_floor?
        #     cur_vel = velocity
        #     cur_vel.y = -500.0_f32
        #     self.velocity = cur_vel
        #   end
        #
        #   # 3. Continuous firing
        #   if Input.action_pressed?("attack")
        #     fire_weapon!
        #   end
        # end
        # ```
        #
        def self.topic_01_polling_input : Nil; end

        # **Sub-Frame FPS Mouse Look**: Smooth 3D first-person camera rotation with InputEventMouseMotion.
        #
        # To achieve competitive-grade, zero-stutter camera look:
        #
        # ```crystal
        # def _ready : Void
        #   # Lock and hide mouse cursor for FPS look:
        #   Input.mouse_mode = Input::MouseMode::Captured
        #
        #   # Disable mouse accumulation for sub-frame raw precision:
        #   Input.use_accumulated_input = false
        # end
        #
        # def _unhandled_input(event : InputEvent) : Void
        #   if motion = event.as?(InputEventMouseMotion)
        #     rotate_y(-motion.relative.x * sensitivity)
        #     camera.rotate_x(-motion.relative.y * sensitivity)
        #   end
        # end
        # ```
        #
        def self.topic_02_mouse_look : Nil; end
      end
    end
  end
end
{% end %}
