# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Scene Tree Manipulation & Node Lifecycle
      #
      # Comprehensive guide to navigating the Godot SceneTree, instantiating nodes, understanding
      # native C++ memory ownership rules, and preventing memory leaks.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>The Two Node Ownership Rules</strong></td>
      #       <td><code>.topic_00_ownership_rules</code></td>
      #       <td>Tree-owned nodes (queue_free) vs standalone unparented nodes (manual .destroy).</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Instantiating Nodes Programmatically</strong></td>
      #       <td><code>.topic_01_creating_nodes</code></td>
      #       <td>Using Godot.create to allocate typed engine nodes and adding to the tree.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Changing Scenes & Tree Queries</strong></td>
      #       <td><code>.topic_02_changing_scenes</code></td>
      #       <td>Accessing the active tree, changing scenes, and finding nodes by path.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Scene Tree Extensions**: `src/libgodot/extensions/scene_tree.cr`
      # - **Live Specs**: `spec/suites/test_scene_tree.cr`
      # - **Ergonomic Node & Path Access**: `Lapis::Docs::C_GAMEPLAY_AND_DECLARATIVE_DSL::G_ERGONOMIC_NODE_ACCESS`
      #
      module E_SCENE_TREE_AND_LIFECYCLE
        # **The Two Node Ownership Rules**: Tree-owned nodes (queue_free) vs standalone unparented nodes (manual .destroy).
        #
        # #### Key Topics & Information
        #
        # - Rule 1: Nodes added to the scene tree (add_child) are owned by Godot; call queue_free
        # - Rule 2: Standalone unparented nodes created via Godot.create are owned by Crystal; call .destroy
        # - Rule 3: RefCounted and Resource objects are managed atomically; never call .destroy
        #
        def self.topic_00_ownership_rules : Nil; end

        # **Instantiating Nodes Programmatically**: Using Godot.create to allocate typed engine nodes and adding to the tree.
        #
        # ```crystal
        # # 1. Create a typed node instance
        # bullet = Godot.create(Godot::Sprite2D)
        # bullet.texture = bullet_texture
        # bullet.position = position
        #
        # # 2. Add to active scene tree (tree assumes ownership)
        # get_parent.not_nil!.add_child(bullet)
        #
        # # 3. Queue deletion at end of frame
        # bullet.queue_free
        # ```
        #
        def self.topic_01_creating_nodes : Nil; end

        # **Changing Scenes & Tree Queries**: Accessing the active tree, changing scenes, and finding nodes by path.
        #
        # ```crystal
        # # Access global SceneTree:
        # tree = get_tree
        #
        # # Change to another scene file:
        # tree.change_scene_to_file("res://scenes/level_02.tscn")
        #
        # # Finding child nodes ergonomically:
        # if hud = self[Godot::Control, "CanvasLayer/HUD"]?
        #   hud.visible = true
        # end
        # ```
        #
        def self.topic_02_changing_scenes : Nil; end
      end
    end
  end
end
{% end %}
