# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module C_GAMEPLAY_AND_DECLARATIVE_DSL
      # # Gameplay Logging & Diagnostics DSL
      #
      # Comprehensive guide to instrumenting Crystal gameplay nodes with high-performance diagnostic logging,
      # custom gameplay domains, telemetry hooks, and zero-allocation release builds.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Gameplay Logging Patterns</strong></td>
      #       <td><code>.topic_00_gameplay_logging_patterns</code></td>
      #       <td>Listing of common architectural patterns for game logging.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Logging Inside Custom Nodes</strong></td>
      #       <td><code>.topic_01_node_logging</code></td>
      #       <td>Invoking Godot.log within node lifecycle methods and physics steps.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Defining Domain-Specific Filters</strong></td>
      #       <td><code>.topic_02_gameplay_filters</code></td>
      #       <td>Grouping logs by game subsystem with custom colors and tags.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Performance Best Practices</strong></td>
      #       <td><code>.topic_03_performance_considerations</code></td>
      #       <td>Ensuring high frame rates with compile-time elision and zero string allocation.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Logging Framework**: `src/libgodot/logging/`
      # - **Gameplay Node DSL**: `src/libgodot/macros.cr`
      # - **Specifications**: `spec/logging_spec.cr`
      #
      module F_GAMEPLAY_LOGGING_AND_SENSORS
        # **Gameplay Logging Patterns**: Listing of common architectural patterns for game logging.
        #
        # #### Key Topics & Information
        #
        # - Combat & Damage Telemetry: Tracking hit points, damage calculation, and weapon attacks
        # - AI State & Pathfinding: Logging behavior tree transitions and navigation milestones
        # - Inventory & Item Transactions: Recording item additions, drops, and crafting events
        # - Network & Multiplayer Replication: Logging RPC dispatches, state synchronization, and packet loss
        #
        def self.topic_00_gameplay_logging_patterns : Nil; end

        # **Logging Inside Custom Nodes**: Invoking Godot.log within node lifecycle methods and physics steps.
        #
        # Within any custom `node` class, use `Godot.log` to record events:
        #
        # ```crystal
        # require "libgodot"
        #
        # node PlayerCharacter < CharacterBody2D do
        #   @[Export]
        #   property max_hp : Int32 = 100
        #
        #   property current_hp : Int32 = 100
        #
        #   signal died
        #
        #   def take_damage(amount : Int32, source : String) : Void
        #     @current_hp = Math.max(0, @current_hp - amount)
        #     Godot.log :combat, "Player took #{amount} damage from #{source} (HP: #{@current_hp}/#{@max_hp})"
        #
        #     if @current_hp == 0
        #       Godot.log :combat, "Player perished!"
        #       died.emit
        #     end
        #   end
        # end
        # ```
        #
        def self.topic_01_node_logging : Nil; end

        # **Defining Domain-Specific Filters**: Grouping logs by game subsystem with custom colors and tags.
        #
        # Declare your game's categories at the top of your system files:
        #
        # ```crystal
        # define_log_filters do
        #   filter :combat,    tag: "{combat}",    name_tag: "COMBAT",    color: "#ff5555"
        #   filter :quest,     tag: "{quest}",     name_tag: "QUEST",     color: "#f1fa8c"
        #   filter :ai,        tag: "{ai}",        name_tag: "AI",        color: "#50fa7b"
        #   filter :dialogue,  tag: "{dialogue}",  name_tag: "DIALOGUE",  color: "#bd93f9"
        # end
        # ```
        #
        # When messages are printed, Godot's output console displays them with clear colored prefixes:
        # ```text
        # [21:45:10.123] [COMBAT] {combat} Player took 25 damage from GoblinArcher (HP: 75/100)
        # [21:45:12.456] [QUEST] {quest} Objective completed: 'Clear the goblin camp'
        # ```
        #
        def self.topic_02_gameplay_filters : Nil; end

        # **Performance Best Practices**: Ensuring high frame rates with compile-time elision and zero string allocation.
        #
        # 1. **Never string-interpolate in hot physics loops without log level guards**:
        #    `Godot.log` macros automatically guard argument evaluation. If `:debug` or `:trace` is disabled at compile time, the entire statement and string interpolation is removed:
        #    ```crystal
        #    # Zero cost in release builds:
        #    Godot.log :trace, "Raycast check at #{global_position} returned #{hit}"
        #    ```
        # 2. **Use Release Compilation for Shipping**:
        #    In `--release` mode, lower severity logs are completely elided.
        #
        def self.topic_03_performance_considerations : Nil; end
      end
    end
  end
end
{% end %}
