# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # CLI Architecture & Global Options
      #
      # The `lapis` CLI is a single, zero-dependency native executable that manages the entire lifecycle
      # of Crystal game development in Godot.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Primary Command Categories</strong></td>
      #       <td><code>.topic_00_core_commands</code></td>
      #       <td>Listing of build, testing, scaffolding, and distribution command groups.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Global Command-Line Flags</strong></td>
      #       <td><code>.topic_01_global_flags</code></td>
      #       <td>Flags accepted by all subcommands across the lapis CLI.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Dynamic Shell Autocompletion</strong></td>
      #       <td><code>.topic_02_shell_completion</code></td>
      #       <td>Generating autocompletion scripts for PowerShell, Bash, and Zsh.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Fuzzy Typo Auto-Correction</strong></td>
      #       <td><code>.topic_03_typo_correction</code></td>
      #       <td>How Lapis detects misspelled commands and suggests corrections.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Main Entry**: `tools/lapis/src/lapis.cr`
      # - **Environment Discovery**: `tools/lapis/src/core/env.cr`
      # - **Related Submodule**: `Docs::B_LAPIS_CLI_AND_TOOLCHAIN::B_DOCTOR`
      #
      module A_OVERVIEW
        # **Primary Command Categories**: Listing of build, testing, scaffolding, and distribution command groups.
        #
        # #### Key Topics & Information
        #
        # - Build & Sync: build, bind, clean, sync, deps, dirs
        # - Testing & Development: doctor, test, editor, run, benchmarks, setup
        # - Scaffolding & Packages: new/scaffold, init, upgrade, addon, shard, ide, package, docs
        # - System & Maintenance: install, uninstall, update, completion, version
        #
        def self.topic_00_core_commands : Nil; end

        # **Global Command-Line Flags**: Flags accepted by all subcommands across the lapis CLI.
        #
        # The `lapis` executable recognizes the following global flags across all subcommands:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Flag</th>
        #       <th>Shorthand</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>--help</code></td>
        #       <td><code>-h</code></td>
        #       <td>Prints detailed help and usage instructions for the current subcommand</td>
        #     </tr>
        #     <tr>
        #       <td><code>--version</code></td>
        #       <td><code>-v</code></td>
        #       <td>Displays the current Lapis toolchain release version and target Godot engine</td>
        #     </tr>
        #     <tr>
        #       <td><code>--verbose</code></td>
        #       <td></td>
        #       <td>Enables verbose debug logging, process commands, and timing metrics</td>
        #     </tr>
        #     <tr>
        #       <td><code>--quiet</code></td>
        #       <td><code>-q</code></td>
        #       <td>Suppresses non-essential terminal output for silent CI execution</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_01_global_flags : Nil; end

        # **Dynamic Shell Autocompletion**: Generating autocompletion scripts for PowerShell, Bash, and Zsh.
        #
        # Lapis features a dynamic completion engine driven by `COMMAND_DESCRIPTIONS`:
        #
        # #### PowerShell Setup:
        # ```powershell
        # lapis completion powershell | Out-String | Invoke-Expression
        # # Or add permanently to your PowerShell $PROFILE:
        # Add-Content $PROFILE 'lapis completion powershell | Out-String | Invoke-Expression'
        # ```
        #
        # #### Bash Setup:
        # ```bash
        # eval "$(lapis completion bash)"
        # # Or add permanently to ~/.bashrc:
        # echo 'eval "$(lapis completion bash)"' >> ~/.bashrc
        # ```
        #
        # #### Zsh Setup:
        # ```zsh
        # eval "$(lapis completion zsh)"
        # # Or add permanently to ~/.zshrc:
        # echo 'eval "$(lapis completion zsh)"' >> ~/.zshrc
        # ```
        #
        def self.topic_02_shell_completion : Nil; end

        # **Fuzzy Typo Auto-Correction**: How Lapis detects misspelled commands and suggests corrections.
        #
        # If you mistype a command (e.g. `lapis bild` instead of `lapis build`), Lapis computes the Levenshtein distance against known commands and provides helpful suggestions:
        #
        # ```text
        # [Lapis:ERROR] Unknown command: 'bild'
        #   Did you mean 'build'?
        # ```
        #
        def self.topic_03_typo_correction : Nil; end
      end
    end
  end
end
{% end %}
