# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Doctor Diagnostic Checker
      #
      # `lapis doctor` audits your system configuration and validates every dependency required
      # for high-performance Crystal game development in Godot.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>The 11 Diagnostic Checks</strong></td>
      #       <td><code>.topic_00_diagnostic_checks</code></td>
      #       <td>Listing of all 11 system and project components validated by doctor.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Command Usage & Options</strong></td>
      #       <td><code>.topic_01_running_doctor</code></td>
      #       <td>How to run doctor and interpret diagnostic markers.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Interpreting Diagnostic Output</strong></td>
      #       <td><code>.topic_02_interpreting_results</code></td>
      #       <td>Understanding check markers [✓], [!], and [✗].</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Resolving Doctor Failures</strong></td>
      #       <td><code>.topic_03_troubleshooting_failures</code></td>
      #       <td>Step-by-step instructions for fixing common doctor diagnostic failures.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Command Implementation**: `tools/lapis/src/commands/doctor.cr`
      # - **Environment Evaluator**: `tools/lapis/src/core/env.cr`
      # - **Live Spec**: `tools/lapis/spec/commands/doctor_spec.cr`
      #
      module B_DOCTOR
        # **The 11 Diagnostic Checks**: Listing of all 11 system and project components validated by doctor.
        #
        # #### Key Topics & Information
        #
        # - 1. Crystal Compiler: Version >= 1.20.0
        # - 2. Godot Engine Executable: Target version 4.8-dev6
        # - 3. C++ Bridge Compiler: MinGW-w64 g++, MSVC cl, or clang
        # - 4. Native Debugger: radare2 executable
        # - 5. Build System: GNU Make >= 4.4
        # - 6. Version Control: Git executable
        # - 7. Crystal Shards: Package manager
        # - 8. Language Server: Crystalline LSP daemon
        # - 9. Windows Packaging: Inno Setup compiler (ISCC.exe on Windows)
        # - 10. Runtime Libraries: gc.dll, pcre2-8.dll, iconv-2.dll, libgodot.dll
        # - 11. Project Configuration: project.godot GDExtension integration
        #
        def self.topic_00_diagnostic_checks : Nil; end

        # **Command Usage & Options**: How to run doctor and interpret diagnostic markers.
        #
        # Run doctor at any time from your project root:
        #
        # ```bash
        # lapis doctor
        # ```
        #
        # #### Options:
        # - `autofix, -f, --fix`: Automatically triage and remediate detectable warnings, missing tools & gaps.
        # - `-v, --verbose`: Display extended diagnostic information.
        # - `-h, --help`: Show help screen.
        #
        def self.topic_01_running_doctor : Nil; end

        # **Interpreting Diagnostic Output**: Understanding check markers [✓], [!], and [✗].
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Marker</th>
        #       <th>Status</th>
        #       <th>Meaning</th>
        #       <th>Action Required</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td><code>[✓]</code></td>
        #       <td><strong>Passed</strong></td>
        #       <td>Component verified and operational</td>
        #       <td>None</td>
        #     </tr>
        #     <tr>
        #       <td><code>[!]</code></td>
        #       <td><strong>Warning</strong></td>
        #       <td>Optional component missing or outdated</td>
        #       <td>Install for enhanced features (e.g. Inno Setup)</td>
        #     </tr>
        #     <tr>
        #       <td><code>[✗]</code></td>
        #       <td><strong>Failure</strong></td>
        #       <td>Required component missing or broken</td>
        #       <td>Must be resolved before building games</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_02_interpreting_results : Nil; end

        # **Resolving Doctor Failures**: Step-by-step instructions for fixing common doctor diagnostic failures.
        #
        # #### 1. Failure: Missing C++ Bridge Compiler
        # - **Cause**: `g++` is not present in your system `PATH`.
        # - **Solution**: Install MinGW-w64 via Scoop (`scoop install gcc`) or MSYS2, then verify with `g++ --version`.
        #
        # #### 2. Failure: Missing Native Debugger (radare2)
        # - **Cause**: radare2 is missing from PATH.
        # - **Solution**: Install radare2 (`scoop install radare2` or `winget install radare2.radare2`).
        #
        # #### 3. Warning: Inno Setup Compiler Missing
        # - **Cause**: `ISCC.exe` not found.
        # - **Note**: Only required if building the Windows standalone installer (`lapis package installer`). Standard game exports (`lapis package game`) do not require Inno Setup.
        #
        def self.topic_03_troubleshooting_failures : Nil; end
      end
    end
  end
end
{% end %}
