# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Project Initialization & Scaffolding
      #
      # Complete guide to scaffolding brand new Crystal Godot games, redistributable GDExtension addons,
      # or integrating Crystal into an existing GDScript project.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Available Scaffolding Modes</strong></td>
      #       <td><code>.topic_00_scaffolding_targets</code></td>
      #       <td>Listing of project archetypes that can be generated.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis init: Existing Project Integration</strong></td>
      #       <td><code>.topic_01_init_command</code></td>
      #       <td>Adding Crystal support to an existing Godot 4.x project without disrupting GDScript.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis new game: Scaffolding a Game</strong></td>
      #       <td><code>.topic_02_new_game</code></td>
      #       <td>Generating a fresh, production-ready standalone game project.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis new addon: Scaffolding an Addon</strong></td>
      #       <td><code>.topic_03_new_addon</code></td>
      #       <td>Creating a redistributable GDExtension plugin for the Godot Asset Library.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Init Implementation**: `tools/lapis/src/commands/init.cr`
      # - **Scaffold Implementation**: `tools/lapis/src/commands/scaffold.cr`
      # - **Templates**: `template/`, `template-addon/`
      #
      module C_INIT_AND_SCAFFOLD
        # **Available Scaffolding Modes**: Listing of project archetypes that can be generated.
        #
        # #### Key Topics & Information
        #
        # - Standalone Game: lapis new game <name>
        # - GDExtension Addon: lapis new addon <name>
        # - Showcase Example: lapis new example <name>
        # - Existing Project Integration: lapis init
        #
        def self.topic_00_scaffolding_targets : Nil; end

        # **lapis init: Existing Project Integration**: Adding Crystal support to an existing Godot 4.x project without disrupting GDScript.
        #
        # If you already have a Godot project and want to write high-performance nodes in Crystal:
        #
        # ```bash
        # cd my_godot_project
        # lapis init
        # ```
        #
        # #### What `lapis init` Does:
        # 1. Generates `shard.yml` with dependencies on `libgodot`.
        # 2. Creates `src/main.cr` with a sample node definition.
        # 3. Stages `addons/crystal_integration` and configures `project.godot` to load it.
        # 4. Staged runtime dependencies into `bin/`.
        # 5. Configures `.gdignore` inside `lib/` and build directories to prevent Godot from scanning Crystal dependencies.
        #
        def self.topic_01_init_command : Nil; end

        # **lapis new game: Scaffolding a Game**: Generating a fresh, production-ready standalone game project.
        #
        # To scaffold a new game project:
        #
        # ```bash
        # lapis new game space_invaders [options]
        # ```
        #
        # #### Options:
        # - `-d, --dir=PATH`: Custom destination directory (default: `./<name>`).
        # - `--author="Name <email>"`: Author metadata for `shard.yml`.
        # - `--desc="Description"`: Game description.
        # - `--skip-shards`: Skip initial `shards install`.
        #
        def self.topic_02_new_game : Nil; end

        # **lapis new addon: Scaffolding an Addon**: Creating a redistributable GDExtension plugin for the Godot Asset Library.
        #
        # To create a plugin or library intended for other Godot developers:
        #
        # ```bash
        # lapis new addon dialogue_graph
        # ```
        #
        # #### Addon Architecture:
        # - Generates `addons/<name>/plugin.cfg` and `plugin.gd`.
        # - Contains a custom `EditorPlugin` node.
        # - Sets up isolated packaging rules so your addon can be distributed as a standalone `.zip`.
        #
        def self.topic_03_new_addon : Nil; end
      end
    end
  end
end
{% end %}
