# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Build & Synchronization Commands
      #
      # Comprehensive reference for `lapis build` and `lapis sync`, covering compilation modes,
      # flags, optimizations, and multi-consumer binary orchestration.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Supported Build Targets</strong></td>
      #       <td><code>.topic_00_build_targets</code></td>
      #       <td>Listing of compilable artifacts: game, plugin, standalone, and templates.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis build: Compilation Modes & Flags</strong></td>
      #       <td><code>.topic_01_build_command</code></td>
      #       <td>Command syntax, compilation flags, release optimizations, and single-module options.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis sync: Multi-Target Synchronization</strong></td>
      #       <td><code>.topic_02_sync_command</code></td>
      #       <td>Ensuring all consumer projects share identical binary deliverables and manifests.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Build Command**: `tools/lapis/src/commands/build.cr`
      # - **Sync Command**: `tools/lapis/src/commands/sync.cr`
      # - **Live Spec**: `tools/lapis/spec/commands/build_spec.cr`
      #
      module D_BUILD_AND_SYNC
        # **Supported Build Targets**: Listing of compilable artifacts: game, plugin, standalone, and templates.
        #
        # #### Key Topics & Information
        #
        # - game: Primary game shared library (bin/game.dll/so/dylib)
        # - plugin: Editor integration plugin (bin/plugin.dll/so/dylib)
        # - standalone: Self-contained LibGodot host executable (bin/game.exe)
        # - examples: All showcase projects under examples/
        # - template: Starter template project
        #
        def self.topic_00_build_targets : Nil; end

        # **lapis build: Compilation Modes & Flags**: Command syntax, compilation flags, release optimizations, and single-module options.
        #
        # #### Usage:
        # ```bash
        # lapis build [target] [options]
        # ```
        #
        # #### Common Options:
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Option</th>
        #       <th>Shorthand</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`--release`</td>
        #       <td>`-r`</td>
        #       <td>Compiles with `--release -O3` optimizations and strips debug symbols</td>
        #     </tr>
        #     <tr>
        #       <td>`--single-module`</td>
        #       <td>`-m`</td>
        #       <td>Compiles via a single LLVM module for maximum cross-module optimization</td>
        #     </tr>
        #     <tr>
        #       <td>`--clean`</td>
        #       <td>`-c`</td>
        #       <td>Removes previous build artifacts before compiling</td>
        #     </tr>
        #     <tr>
        #       <td>`--threads=N`</td>
        #       <td></td>
        #       <td>Sets the number of parallel Crystal compilation threads</td>
        #     </tr>
        #     <tr>
        #       <td>`--error-trace`</td>
        #       <td></td>
        #       <td>Prints full exception backtraces on compilation errors</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Examples:
        # ```bash
        # lapis build game                # Fast incremental debug build of game.dll
        # lapis build game -r             # Production release build
        # lapis build standalone -r -m    # Optimized single-module standalone executable
        # ```
        #
        def self.topic_01_build_command : Nil; end

        # **lapis sync: Multi-Target Synchronization**: Ensuring all consumer projects share identical binary deliverables and manifests.
        #
        # In a monorepo or multi-project workspace, different projects (e.g. `examples/basic_demo`, `template/`, `performance/`) require runtime shared libraries and manifests:
        #
        # ```bash
        # lapis sync [options]
        # ```
        #
        # #### What `lapis sync` Performs:
        # 1. Verifies `bin/crystal_bridge.dll` and copies to consumer `bin/` directories.
        # 2. Validates runtime dependencies (`gc.dll`, `pcre2-8.dll`, `iconv-2.dll`, `libgodot.dll`).
        # 3. Synchronizes GDExtension manifests (`crystal.gdextension`).
        # 4. Enforces `.gdignore` placement inside `lib/` and output directories.
        #
        def self.topic_02_sync_command : Nil; end
      end
    end
  end
end
{% end %}
