# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Workspace Cleaning & Disk Reclamation
      #
      # Comprehensive guide to cleaning build artifacts and reclaiming disk space with `lapis clean`,
      # highlighting automated protections for nested git subprojects and runtime shared libraries.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Clean Operational Modes</strong></td>
      #       <td><code>.topic_00_clean_modes</code></td>
      #       <td>Standard clean, shadow DLL pruning, full purge, and dry-run preview.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis clean: Options & Flags</strong></td>
      #       <td><code>.topic_01_command_options</code></td>
      #       <td>Command-line syntax and option reference.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Subproject & Git Protection Invariants</strong></td>
      #       <td><code>.topic_02_safety_guards</code></td>
      #       <td>How lapis clean protects checked-out repositories and critical runtime dependencies.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Sample Clean Outputs</strong></td>
      #       <td><code>.topic_03_expected_output</code></td>
      #       <td>Terminal output during dry-run and shadow reclamation.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Clean Implementation**: `tools/lapis/src/commands/clean.cr`
      # - **Live Spec**: `tools/lapis/spec/commands/clean_spec.cr`
      #
      module F_CLEAN_AND_MAINTENANCE
        # **Clean Operational Modes**: Standard clean, shadow DLL pruning, full purge, and dry-run preview.
        #
        # #### Key Topics & Information
        #
        # - Standard clean: lapis clean (removes compiled game/plugin binaries, keeps runtime DLLs)
        # - Shadow pruning: lapis clean --shadows (prunes only temporary *_loaded_* DLLs and PDBs)
        # - Dry-run preview: lapis clean --dry-run (computes files and bytes to reclaim without deleting)
        # - Full purge: lapis clean --all (removes intermediate build caches, shadow DLLs, and test remnants)
        #
        def self.topic_00_clean_modes : Nil; end

        # **lapis clean: Options & Flags**: Command-line syntax and option reference.
        #
        # #### Usage:
        # ```bash
        # lapis clean [options]
        # ```
        #
        # #### Options:
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Option</th>
        #       <th>Shorthand</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`--shadows`</td>
        #       <td>`-s`</td>
        #       <td>Prunes only stale Windows shadow DLLs (`*_loaded_*.dll/pdb`)</td>
        #     </tr>
        #     <tr>
        #       <td>`--dry-run`</td>
        #       <td>`-n`</td>
        #       <td>Previews files and exact disk space to be freed without deleting</td>
        #     </tr>
        #     <tr>
        #       <td>`--all`</td>
        #       <td>`-a`</td>
        #       <td>Comprehensive clean including build caches and intermediate files</td>
        #     </tr>
        #     <tr>
        #       <td>`--docs`</td>
        #       <td></td>
        #       <td>Also removes generated `docs/` HTML manual</td>
        #     </tr>
        #     <tr>
        #       <td>`-p, --project=DIR`</td>
        #       <td></td>
        #       <td>Target specific project directory (default: current directory)</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_01_command_options : Nil; end

        # **Subproject & Git Protection Invariants**: How lapis clean protects checked-out repositories and critical runtime dependencies.
        #
        # To prevent accidental data loss:
        # 1. **Subproject Repository Protection**: `clean_bin_dir` inspects each folder inside `bin/` and skips any directory containing `.git` or `.gitkeep`. Even if you check out a repository inside `bin/` (e.g. `bin/crshader`), `lapis clean` will never delete it!
        # 2. **Runtime DLL Preservation**: Core shared libraries (`gc.dll`, `pcre2-8.dll`, `iconv-2.dll`, `libgodot.dll`) are never deleted by standard clean.
        # 3. **Documentation Protection**: The `docs/` folder is preserved by default and is only removed if `--docs` or `--all` is explicitly passed.
        #
        def self.topic_02_safety_guards : Nil; end

        # **Sample Clean Outputs**: Terminal output during dry-run and shadow reclamation.
        #
        # #### Running Shadow Pruning:
        # ```bash
        # lapis clean --shadows
        # ```
        # ```text
        # [Clean] Cleaning stale shadow DLLs (*_loaded_*) across workspace...
        # [Lapis] Shadow libraries cleaned successfully! Reclaimed 24.79 GB across 1727 file(s).
        # ```
        #
        # #### Running Dry-Run:
        # ```bash
        # lapis clean --dry-run
        # ```
        # ```text
        # [Clean:DryRun] Scanning workspace for removable artifacts...
        #   Candidate: bin/game.dll (28.45 MB)
        #   Candidate: bin/plugin.dll (14.20 MB)
        # [Clean:DryRun] Dry run complete: 2 file(s) would be removed, reclaiming 42.65 MB.
        # ```
        #
        def self.topic_03_expected_output : Nil; end
      end
    end
  end
end
{% end %}
