# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Addon & Shard Dependency Management
      #
      # Comprehensive guide to adding, updating, and removing community GDExtension addons
      # and Crystal shard packages in your Godot project.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>The Two Dependency Types</strong></td>
      #       <td><code>.topic_00_package_types</code></td>
      #       <td>Godot GDExtension Addons (in addons/) vs Crystal Shards (in shard.yml).</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis addon: Installing GDExtensions</strong></td>
      #       <td><code>.topic_01_addon_installation</code></td>
      #       <td>Installing precompiled addons or compiling from GitHub repositories.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis addon uninstall: Clean Removal</strong></td>
      #       <td><code>.topic_02_addon_uninstallation</code></td>
      #       <td>Disabling and removing an addon cleanly from project configuration.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis shard: Managing Crystal Dependencies</strong></td>
      #       <td><code>.topic_03_shard_management</code></td>
      #       <td>Listing, adding, removing, and pruning Crystal shard dependencies.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Addon Installer**: `tools/lapis/src/commands/install_addon.cr`
      # - **Shard Manager**: `tools/lapis/src/commands/shard_manager.cr`
      # - **Live Specs**: `spec/lapis_install_addon_spec.cr`
      #
      module G_ADDON_AND_SHARD_MANAGEMENT
        # **The Two Dependency Types**: Godot GDExtension Addons (in addons/) vs Crystal Shards (in shard.yml).
        #
        # #### Key Topics & Information
        #
        # - GDExtension Addons: Binary plugins loaded by Godot Engine (managed via lapis addon)
        # - Crystal Shards: Compiled language libraries & dependencies (managed via lapis shard)
        #
        def self.topic_00_package_types : Nil; end

        # **lapis addon: Installing GDExtensions**: Installing precompiled addons or compiling from GitHub repositories.
        #
        # To install a GDExtension addon into your Godot project:
        #
        # ```bash
        # # List installed addons and activation status:
        # lapis addon list
        #
        # # Install from GitHub repository:
        # lapis addon install github:owner/repo
        #
        # # Install specific release tag:
        # lapis addon install github:owner/repo@v1.2.0
        #
        # # Install from local archive:
        # lapis addon install path/to/addon.zip
        # ```
        #
        # #### What Happens Automatically:
        # 1. Downloads and extracts the addon into `addons/<name>`.
        # 2. Validates GDExtension manifests (`<name>.gdextension`).
        # 3. Stages required runtime libraries (`gc.dll`, `pcre2-8.dll`, `iconv-2.dll`).
        # 4. Registers and enables the plugin in `project.godot`.
        # 5. Tracks the addon in `shard.yml` under `addons:`.
        #
        def self.topic_01_addon_installation : Nil; end

        # **lapis addon uninstall: Clean Removal**: Disabling and removing an addon cleanly from project configuration.
        #
        # To remove an installed addon:
        #
        # ```bash
        # lapis addon uninstall <name>
        # ```
        #
        # Lapis cleanly disables the plugin in `project.godot`, removes the directory from `addons/`, and untracks it from `shard.yml`.
        #
        def self.topic_02_addon_uninstallation : Nil; end

        # **lapis shard: Managing Crystal Dependencies**: Listing, adding, removing, and pruning Crystal shard dependencies.
        #
        # To manage standard Crystal packages in `shard.yml`:
        #
        # ```bash
        # # List declared dependencies and installation status:
        # lapis shard list
        #
        # # Add a GitHub dependency:
        # lapis shard add github:crystal-community/compress
        #
        # # Add with version constraint:
        # lapis shard add crystal-community/compress@~>1.0.0
        #
        # # Remove a dependency:
        # lapis shard remove compress
        #
        # # Prune unreferenced libraries:
        # lapis shard prune
        # ```
        #
        def self.topic_03_shard_management : Nil; end
      end
    end
  end
end
{% end %}
