# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # IDE Integration & Language Server (LSP)
      #
      # Comprehensive guide to configuring modern code editors with rich Crystal syntax highlighting,
      # hover documentation, auto-completion, and native radare2 debugging with `lapis ide`.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Supported Code Editors</strong></td>
      #       <td><code>.topic_00_supported_editors</code></td>
      #       <td>One-click setup for VS Code, Cursor, Zed, and Neovim.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis ide: Automated Configuration</strong></td>
      #       <td><code>.topic_01_ide_setup_command</code></td>
      #       <td>Generating optimal editor settings and debug launch profiles with a single command.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Crystalline LSP Capabilities</strong></td>
      #       <td><code>.topic_02_crystalline_capabilities</code></td>
      #       <td>Contextual autocomplete, hover tooltips, go-to-definition, and inline diagnostics.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **IDE Setup**: `tools/lapis/src/commands/ide.cr`
      # - **LSP Integration**: `src/libgodot/script/crystal_language.cr`
      # - **Live Spec**: `spec/suites/test_ide_lsp.cr`
      #
      module H_IDE_AND_LSP
        # **Supported Code Editors**: One-click setup for VS Code, Cursor, Zed, and Neovim.
        #
        # #### Key Topics & Information
        #
        # - Visual Studio Code (.vscode/settings.json, launch.json, tasks.json)
        # - Cursor (AI-assisted editor with VS Code compatibility)
        # - Zed (.zed/settings.json with native Crystalline LSP)
        # - Neovim (nvim-lspconfig configuration with stdio framing)
        #
        def self.topic_00_supported_editors : Nil; end

        # **lapis ide: Automated Configuration**: Generating optimal editor settings and debug launch profiles with a single command.
        #
        # Run `lapis ide` in your project root:
        #
        # ```bash
        # lapis ide [editor] [options]
        # ```
        #
        # #### Supported Editor Arguments:
        # - `lapis ide vscode`: Configures VS Code / Cursor.
        # - `lapis ide zed`: Configures Zed editor.
        # - `lapis ide neovim`: Generates Lua snippet for `nvim-lspconfig`.
        # - `lapis ide --all`: Configures all supported IDEs simultaneously.
        #
        # #### What is Configured Automatically:
        # 1. Sets Crystalline executable path in editor settings.
        # 2. Configures debug profiles in `.vscode/launch.json`:
        #    - `Run Godot Game`
        #    - `Open Godot Editor`
        #    - `Debug Godot Game (radare2)`
        # 3. Adds build tasks in `.vscode/tasks.json` (`lapis build game`, `lapis run`).
        #
        def self.topic_01_ide_setup_command : Nil; end

        # **Crystalline LSP Capabilities**: Contextual autocomplete, hover tooltips, go-to-definition, and inline diagnostics.
        #
        # With Crystalline LSP enabled:
        # - **Contextual Autocomplete**: Autocomplete proposals for Godot engine classes (`Node2D`, `CharacterBody3D`), methods, and custom Crystal nodes.
        # - **Hover Documentation**: Hovering over any Godot method displays the official Godot engine docstring and Crystal type signature.
        # - **Go to Definition**: Jump directly from a method call to its definition in Crystal or engine bindings.
        # - **Inline Compiler Diagnostics**: Red squiggly lines appear under syntax errors and type mismatches in real-time as you type.
        #
        def self.topic_02_crystalline_capabilities : Nil; end
      end
    end
  end
end
{% end %}
