# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Packaging & Release Distribution
      #
      # Comprehensive guide to exporting and packaging your finished game or redistributable addon
      # with `lapis package`.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Distribution Formats</strong></td>
      #       <td><code>.topic_00_package_formats</code></td>
      #       <td>Supported export targets: game, addon, installer, deb, and full release.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis package game: Standalone Export</strong></td>
      #       <td><code>.topic_01_package_game</code></td>
      #       <td>Bundling a playable game executable for Windows, Linux, or macOS.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis package installer: Windows Setup</strong></td>
      #       <td><code>.topic_02_windows_installer</code></td>
      #       <td>Compiling an Inno Setup installer executable with Crystalline and desktop shortcuts.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>lapis package deb: Linux Distribution</strong></td>
      #       <td><code>.topic_03_debian_package</code></td>
      #       <td>Generating a signed, standard .deb package for Debian, Ubuntu, and Mint.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Package Command**: `tools/lapis/src/commands/package.cr`
      # - **Installer Script**: `rsrc/installer/lapis_installer.iss`
      # - **Live Spec**: `tools/lapis/spec/commands/package_spec.cr`
      #
      module I_PACKAGING_AND_DISTRIBUTION
        # **Distribution Formats**: Supported export targets: game, addon, installer, deb, and full release.
        #
        # #### Key Topics & Information
        #
        # - Playable Game: lapis package game (self-contained executable + embedded PCK)
        # - Addon Zip: lapis package addon (clean redistributable archive for AssetLib)
        # - Windows Installer: lapis package installer (Inno Setup executable)
        # - Debian Package: lapis package deb (.deb for Ubuntu/Debian)
        # - Release Distribution: lapis package release (full distribution archives + SHA256)
        #
        def self.topic_00_package_formats : Nil; end

        # **lapis package game: Standalone Export**: Bundling a playable game executable for Windows, Linux, or macOS.
        #
        # To package your game into a single playable bundle:
        #
        # ```bash
        # lapis package game [options]
        # ```
        #
        # #### Options:
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Option</th>
        #       <th>Shorthand</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`--release`</td>
        #       <td>`-r`</td>
        #       <td>Builds with release optimizations and strips debug symbols</td>
        #     </tr>
        #     <tr>
        #       <td>`--embedded`</td>
        #       <td></td>
        #       <td>Embeds game PCK data directly into the executable binary</td>
        #     </tr>
        #     <tr>
        #       <td>`--output=DIR`</td>
        #       <td>`-o`</td>
        #       <td>Destination directory (default: `dist/`)</td>
        #     </tr>
        #     <tr>
        #       <td>`--force`</td>
        #       <td>`-f`</td>
        #       <td>Overwrite existing distribution files</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_01_package_game : Nil; end

        # **lapis package installer: Windows Setup**: Compiling an Inno Setup installer executable with Crystalline and desktop shortcuts.
        #
        # If you are distributing tooling or a complete development suite on Windows:
        #
        # ```bash
        # lapis package installer
        # ```
        #
        # Compiles `lapis-setup-windows-x86_64.exe` using Inno Setup (`ISCC.exe`), bundling the `lapis` executable, Crystalline LSP, runtime dependencies (`gc.dll`, `pcre2-8.dll`, `iconv-2.dll`), and configuring user `PATH`.
        #
        def self.topic_02_windows_installer : Nil; end

        # **lapis package deb: Linux Distribution**: Generating a signed, standard .deb package for Debian, Ubuntu, and Mint.
        #
        # On Linux, generate a standard `.deb` archive:
        #
        # ```bash
        # lapis package deb
        # ```
        #
        # Stages the binary into `/usr/bin/lapis`, configures man pages, and sets up package control metadata in `bin/release_dist/`.
        #
        def self.topic_03_debian_package : Nil; end
      end
    end
  end
end
{% end %}
