# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Logging Framework & Telemetry
      #
      # Comprehensive guide to the Lapis logging and telemetry apparatus, covering runtime severity levels,
      # the metaprogrammed `define_log_filters` DSL, compile-time zero-cost log elision, and the `lapis log` CLI tool.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Core Logging Capabilities</strong></td>
      #       <td><code>.topic_00_logging_features</code></td>
      #       <td>High-performance features of the Lapis diagnostic logging system.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Godot.log & Severity Levels</strong></td>
      #       <td><code>.topic_01_godot_log_dsl</code></td>
      #       <td>Writing structured log messages across standard severity levels.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Custom Domain Filters & Tags</strong></td>
      #       <td><code>.topic_02_custom_filters_and_tags</code></td>
      #       <td>Declaring project-specific log categories using define_log_filters and log_filter.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Compile-Time Log Elision & Optimization</strong></td>
      #       <td><code>.topic_03_compile_time_elision</code></td>
      #       <td>Stripping low-priority logs at compile time to eliminate string allocations.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>CLI Log Streaming with lapis log</strong></td>
      #       <td><code>.topic_04_lapis_log_cli</code></td>
      #       <td>Inspecting, streaming, and filtering game logs from the terminal.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Logging Implementation**: `src/libgodot/logging/`
      # - **Log CLI Command**: `tools/lapis/src/commands/log.cr`
      # - **Specifications**: `spec/logging_spec.cr`
      #
      module K_LOGGING_AND_TELEMETRY
        # **Core Logging Capabilities**: High-performance features of the Lapis diagnostic logging system.
        #
        # #### Key Topics & Information
        #
        # - Zero-Cost Compile-Time Elision: Unused logs produce 0 bytes in output binaries
        # - Metaprogrammed Filter DSL: define_log_filters creates typed enum values and dispatchers
        # - BBCode Console Formatting: Rich color highlights for Godot editor output dock
        # - Structured Records: Captures timestamp, severity, tag, channel, callsite file and line
        # - CLI Streaming & Inspection: lapis log tails, filters, and formats logs with ANSI colors
        #
        def self.topic_00_logging_features : Nil; end

        # **Godotlog & Severity Levels**: Writing structured log messages across standard severity levels.
        #
        # Lapis provides built-in logging methods on `Godot`:
        #
        # ```crystal
        # require "libgodot"
        #
        # # Standard logging methods:
        # Godot.error("Failed to load map data", "LevelLoader")
        # Godot.warn("High frame time detected: #{delta * 1000} ms")
        # Godot.info("Player spawned at #{position}")
        # Godot.debug("Velocity: #{velocity}")
        # Godot.trace("Sub-frame physics iteration")
        # ```
        #
        # Or via `Godot.log` with a level symbol or enum:
        # ```crystal
        # Godot.log :info, "Audio bus initialized"
        # Godot.log Godot::LogLevel::Warn, "Texture cache nearing limit"
        # ```
        #
        def self.topic_01_godot_log_dsl : Nil; end

        # **Custom Domain Filters & Tags**: Declaring project-specific log categories using define_log_filters and log_filter.
        #
        # Use `define_log_filters` to register domain-specific categories with custom BBCode hex colors and tags:
        #
        # ```crystal
        # define_log_filters do
        #   filter :combat,    tag: "{combat}",    name_tag: "COMBAT",    color: "#ff5555"
        #   filter :ai,        tag: "{ai}",        name_tag: "AI",        color: "#50fa7b"
        #   filter :dialogue,  tag: "{dialogue}",  name_tag: "DIALOGUE",  color: "#bd93f9"
        #   filter :net,       tag: "{net}",       name_tag: "NETWORK",   color: "#8be9fd"
        # end
        #
        # # In your gameplay nodes:
        # Godot.log :combat, "Fireball dealt 45 damage to #{target.name}"
        # Godot.log :dialogue, "NPC greeting started: 'Welcome stranger!'"
        # ```
        #
        # Or declare a single filter directly at the top of a file:
        # ```crystal
        # log_filter :inventory, tag: "{inv}", name_tag: "INVENTORY", color: "#f1fa8c"
        # ```
        #
        def self.topic_02_custom_filters_and_tags : Nil; end

        # **Compile-Time Log Elision & Optimization**: Stripping low-priority logs at compile time to eliminate string allocations.
        #
        # In production builds or performance-sensitive loops, log formatting overhead must not impact frame rate.
        # Lapis evaluates log statements through Crystal macros:
        #
        # - In `--release` builds, debug and trace logs are completely removed from the abstract syntax tree.
        # - Expressions passed to `Godot.log` (such as string interpolations `"Value: #{expensive_calc}"`) are never executed if the log level is disabled.
        # - You can specify a custom compile-time log threshold via compiler flag:
        #   ```bash
        #   crystal build src/main.cr -Dlog_level=warn
        #   ```
        #
        def self.topic_03_compile_time_elision : Nil; end

        # **CLI Log Streaming with lapis log**: Inspecting, streaming, and filtering game logs from the terminal.
        #
        # Use the `lapis log` CLI command to monitor game execution:
        #
        # ```bash
        # # Follow live game log output in real time
        # lapis log --tail
        #
        # # Filter by minimum severity level
        # lapis log --level=WARN
        #
        # # Filter by custom tag or channel
        # lapis log --filter=combat
        #
        # # Output formatted with ANSI terminal escape colors
        # lapis log --ansi
        #
        # # View the last 50 log records
        # lapis log --lines=50
        # ```
        #
        def self.topic_04_lapis_log_cli : Nil; end
      end
    end
  end
end
{% end %}
