# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Compile-Time Flags & Optimization
      #
      # Comprehensive guide to compile-time configuration flags across Lapis, covering binary size optimization,
      # thread-safety check elision, and opt-in diagnostic instrumentation for memory leaks, signals, and dispatches.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Compile-Time Flag Matrix</strong></td>
      #       <td><code>.topic_00_optimization_flags</code></td>
      #       <td>Listing of binary stripping and diagnostic compiler switches.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Producing Ultra-Lean Production Binaries</strong></td>
      #       <td><code>.topic_01_stripping_lean_binaries</code></td>
      #       <td>Stripping docstrings, XML help registries, and test scaffolding.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>High-Throughput Thread-Safety Bypass</strong></td>
      #       <td><code>.topic_02_thread_safety_bypass</code></td>
      #       <td>Eliminating main-thread assertions for maximum scene graph dispatch speed.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Opt-In Diagnostic Instrumentation</strong></td>
      #       <td><code>.topic_03_diagnostic_instrumentation</code></td>
      #       <td>Enabling memory leak tracking, method dispatch profiling, and dead-pointer callstacks.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>CLI Switches & Environment Variables</strong></td>
      #       <td><code>.topic_04_cli_integration</code></td>
      #       <td>Invoking flags via lapis CLI options or environment variables.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Build Command**: `tools/lapis/src/commands/build.cr`
      # - **Diagnostics Implementation**: `src/libgodot/diagnostics.cr`
      # - **Specifications**: `spec/compile_flags_spec.cr`
      #
      module L_COMPILE_FLAGS_AND_OPTIMIZATION
        # **Compile-Time Flag Matrix**: Listing of binary stripping and diagnostic compiler switches.
        #
        # #### Key Topics & Information
        #
        # - --strip-docs (-Dno_doc): Strips doc comments and EditorHelp XML strings
        # - --no-thread-safety (-Dno_thread_safety): Bypasses main-thread runtime guards
        # - --no-testing (-Dno_testing): Excludes test suites from consumer deliverables
        # - --no-crash-handler (-Dno_crash_handler): Disables Windows VEH handler for clean radare2 execution
        # - --leak-tracker (-Dleak_tracker): Tracks object allocations, call sites, and surviving instances
        # - --profile-dispatches (-Dprofile_dispatches): Records nanosecond virtual method dispatch latency
        # - --trace-dead-pointers (-Dtrace_dead_pointers): Maintains deallocation callstacks for DisposedObjectError
        # - --trace-signals (-Dtrace_signals): Intercepts and logs scene tree signal emissions
        #
        def self.topic_00_optimization_flags : Nil; end

        # **Producing Ultra-Lean Production Binaries**: Stripping docstrings, XML help registries, and test scaffolding.
        #
        # During release compilation, binary size can be minimized by stripping metadata unnecessary for runtime gameplay:
        #
        # ```bash
        # # Strip docs, XML help, and test scaffolding
        # lapis build --release --strip-docs --no-testing
        # ```
        #
        # - **`--strip-docs` (`-Dno_doc`)**: Strips out hundreds of kilobytes of extracted doc comments and XML help structures from `src/libgodot/macros.cr` and `src/libgodot/doc_macro.cr`. Automatically enabled in `--release`.
        # - **`--no-testing` (`-Dno_testing`)**: Omit test runners and benchmark harnesses from consumer games.
        #
        def self.topic_01_stripping_lean_binaries : Nil; end

        # **High-Throughput Thread-Safety Bypass**: Eliminating main-thread assertions for maximum scene graph dispatch speed.
        #
        # By default, LibGodot guards scene tree mutations (`add_child`, `remove_child`) with `Godot::ThreadSafety.assert_main_thread!`.
        # For battle-tested, single-threaded game loops, these checks can be completely elided at compile time:
        #
        # ```bash
        # lapis build --release --no-thread-safety
        # ```
        #
        # When compiled with `--no-thread-safety` (or `-Dfast_dispatch`), `assert_main_thread!` becomes a zero-cost compiler no-op, eliminating thread ID queries and branch predictions on hot loops.
        #
        def self.topic_02_thread_safety_bypass : Nil; end

        # **Opt-In Diagnostic Instrumentation**: Enabling memory leak tracking, method dispatch profiling, and dead-pointer callstacks.
        #
        # When debugging complex engine interactions, Lapis provides low-overhead diagnostic modules:
        #
        # #### Memory Leak Tracking:
        # ```bash
        # lapis build --leak-tracker
        # ```
        # Logs every object allocation with source file and line. At shutdown, inspect surviving objects:
        # ```crystal
        # {% if flag?(:leak_tracker) %}
        #   Godot::Diagnostics::LeakTracker.dump_active_objects
        # {% end %}
        # ```
        #
        # #### Virtual Method Dispatch Latency Profiling:
        # ```bash
        # lapis build --profile-dispatches
        # ```
        # Captures invocation count, average nanoseconds, minimum, and maximum latency for all virtual calls into Crystal.
        #
        # #### Dead-Pointer Destruction Callstack History:
        # ```bash
        # lapis build --trace-dead-pointers
        # ```
        # Maintains a ring buffer of deallocated instances so any subsequent `DisposedObjectError` pinpoints where the node was freed.
        #
        def self.topic_03_diagnostic_instrumentation : Nil; end

        # **CLI Switches & Environment Variables**: Invoking flags via lapis CLI options or environment variables.
        #
        # All optimization and diagnostic flags can be specified through CLI switches or environment variables:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Switch</th>
        #       <th>Environment Variable</th>
        #       <th>Crystal Flag</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`--strip-docs`</td>
        #       <td>`STRIP_DOCS=1`</td>
        #       <td>`-Dno_doc`</td>
        #     </tr>
        #     <tr>
        #       <td>`--no-thread-safety`</td>
        #       <td>`NO_THREAD_SAFETY=1`</td>
        #       <td>`-Dno_thread_safety`</td>
        #     </tr>
        #     <tr>
        #       <td>`--leak-tracker`</td>
        #       <td>`LEAK_TRACKER=1`</td>
        #       <td>`-Dleak_tracker`</td>
        #     </tr>
        #     <tr>
        #       <td>`--profile-dispatches`</td>
        #       <td>`PROFILE_DISPATCHES=1`</td>
        #       <td>`-Dprofile_dispatches`</td>
        #     </tr>
        #     <tr>
        #       <td>`--trace-dead-pointers`</td>
        #       <td>`TRACE_DEAD_POINTERS=1`</td>
        #       <td>`-Dtrace_dead_pointers`</td>
        #     </tr>
        #     <tr>
        #       <td>`--trace-signals`</td>
        #       <td>`TRACE_SIGNALS=1`</td>
        #       <td>`-Dtrace_signals`</td>
        #     </tr>
        #     <tr>
        #       <td>`--no-crash-handler`</td>
        #       <td>`NO_CRASH_HANDLER=1`</td>
        #       <td>`-Dno_crash_handler`</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_04_cli_integration : Nil; end
      end
    end
  end
end
{% end %}
