# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module B_LAPIS_CLI_AND_TOOLCHAIN
      # # Addon Store & Security Auditing
      #
      # Comprehensive guide to managing community and third-party GDExtension addons in Lapis,
      # including automated security checks, Git version pinning, vendoring, and project synchronization.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Addon Management Capabilities</strong></td>
      #       <td><code>.topic_00_addon_capabilities</code></td>
      #       <td>Listing of features provided by lapis addon and lapis install-addon.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Installing Addons from Git</strong></td>
      #       <td><code>.topic_01_installing_from_git</code></td>
      #       <td>Cloning and installing community addons with branch and tag pinning.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Automated Security & Integrity Auditing</strong></td>
      #       <td><code>.topic_02_security_auditing</code></td>
      #       <td>How Lapis protects projects from untrusted third-party addon code.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Dependency & Plugin Synchronization</strong></td>
      #       <td><code>.topic_03_dependency_and_plugin_sync</code></td>
      #       <td>Automatic synchronization with shard.yml and project.godot.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Vendoring Addons for Offline Builds</strong></td>
      #       <td><code>.topic_04_vendoring_and_offline_builds</code></td>
      #       <td>Freezing addon source code directly in the repository.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Addon CLI Command**: `tools/lapis/src/commands/install_addon.cr`
      # - **Shard Manager**: `tools/lapis/src/commands/shard_manager.cr`
      # - **Specifications**: `tools/lapis/spec/install_addon_spec.cr`
      #
      module M_ADDON_STORE_AND_SECURITY
        # **Addon Management Capabilities**: Listing of features provided by lapis addon and lapis install-addon.
        #
        # #### Key Topics & Information
        #
        # - Git URL Installation: Clone and install directly from GitHub, GitLab, or Git hosts
        # - Automated Security Audit: Blocks dangerous shell scripts, binaries, and path traversal
        # - Atomic Registration: Updates shard.yml and enables plugin in project.godot
        # - Vendoring Support: Freezes addon source code locally for self-contained repositories
        # - Clean Uninstallation: Removes files and disables plugins without leaving dangling references
        #
        def self.topic_00_addon_capabilities : Nil; end

        # **Installing Addons from Git**: Cloning and installing community addons with branch and tag pinning.
        #
        # To install an addon directly from a Git repository:
        #
        # ```bash
        # # Install latest version
        # lapis addon install https://github.com/sol-vin/lapis_dialogue.git
        #
        # # Pin to a specific release branch or tag
        # lapis addon install https://github.com/sol-vin/lapis_inventory.git --branch=v2.1.0
        #
        # # Install from a local folder during development
        # lapis addon install ../my_local_addon
        # ```
        #
        def self.topic_01_installing_from_git : Nil; end

        # **Automated Security & Integrity Auditing**: How Lapis protects projects from untrusted third-party addon code.
        #
        # Before copying files into `addons/`, Lapis conducts an automated security audit:
        #
        # - **Path Traversal Protection**: Ensures no archive or git symlink escapes outside the target addon folder.
        # - **Script Verification**: Scans for unauthorized executables, obfuscated binaries, or rogue post-install shell scripts.
        # - **ClassDB Conflict Detection**: Checks if custom node names clash with existing engine classes or installed addons.
        #
        def self.topic_02_security_auditing : Nil; end

        # **Dependency & Plugin Synchronization**: Automatic synchronization with shard.yml and project.godot.
        #
        # When an addon is installed or removed, Lapis synchronizes two primary manifests:
        #
        # 1. **`project.godot`**: Automatically appends the plugin path to `editor_plugins/enabled`:
        #    ```ini
        #    [editor_plugins]
        #    enabled=["res://addons/lapis_dialogue/plugin.cfg"]
        #    ```
        # 2. **`shard.yml`**: Tracks the addon version or git dependency under `addons:` and runs `shards install`.
        #
        def self.topic_03_dependency_and_plugin_sync : Nil; end

        # **Vendoring Addons for Offline Builds**: Freezing addon source code directly in the repository.
        #
        # For enterprise game projects or offline air-gapped CI environments:
        #
        # ```bash
        # lapis addon install https://github.com/sol-vin/lapis_dialogue.git --vendor
        # ```
        #
        # The `--vendor` flag extracts the complete source code directly into `addons/` and `src/` without depending on external Git repositories at compile time.
        #
        def self.topic_04_vendoring_and_offline_builds : Nil; end
      end
    end
  end
end
{% end %}
