# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module F_SCRIPTING_AND_INTEROPERABILITY
      # # First-Class Crystal Scripts in Godot Editor
      #
      # Comprehensive guide to Lapis's first-class scripting engine, enabling developers to write,
      # attach, and edit `.cr` scripts inside the Godot Editor exactly like GDScript or C#.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Scripting Capabilities</strong></td>
      #       <td><code>.topic_00_scripting_features</code></td>
      #       <td>Native ScriptLanguage integration, syntax highlighting, and live AST inspection.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Attaching .cr Scripts to Nodes</strong></td>
      #       <td><code>.topic_01_attaching_scripts</code></td>
      #       <td>Creating and attaching Crystal scripts via the Godot Editor UI.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Crystal Script**: `src/libgodot/script/crystal_script.cr`
      # - **Syntax Highlighter**: `src/libgodot/script/crystal_highlighter.cr`
      # - **Live Specs**: `spec/suites/test_script_first_class.cr`
      #
      module A_FIRST_CLASS_CRYSTAL_SCRIPTS
        # **Scripting Capabilities**: Native ScriptLanguage integration, syntax highlighting, and live AST inspection.
        #
        # #### Key Topics & Information
        #
        # - Full ScriptLanguage registration in Godot Engine
        # - Create .cr files from the standard Godot Attach Script dialog
        # - Pure Crystal syntax highlighter embedded in the Script Editor
        # - Crystalline LSP code completion proposals and documentation hover
        #
        def self.topic_00_scripting_features : Nil; end

        # **Attaching cr Scripts to Nodes**: Creating and attaching Crystal scripts via the Godot Editor UI.
        #
        # 1. In Godot's Scene dock, right click any node and select **Attach Script**.
        # 2. In the Language dropdown, select **Crystal** (`.cr`).
        # 3. Godot automatically creates the `.cr` file with proper node template and attaches it to the node.
        # 4. Double-click the script to open it in Godot's built-in Script Editor!
        #
        def self.topic_01_attaching_scripts : Nil; end
      end
    end
  end
end
{% end %}
