# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module F_SCRIPTING_AND_INTEROPERABILITY
      # # GDScript Interoperability & Project Bindings
      #
      # Comprehensive guide to calling GDScript functions from Crystal, invoking Crystal methods
      # from GDScript, and generating strongly-typed wrappers for custom project nodes with `lapis bind`.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Interoperability Modalities</strong></td>
      #       <td><code>.topic_00_interop_modes</code></td>
      #       <td>Dynamic reflection calls vs compile-time strongly-typed project bindings.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Automated Typed Project Bindings (lapis bind)</strong></td>
      #       <td><code>.topic_01_typed_project_bindings</code></td>
      #       <td>Generating strongly-typed Crystal wrappers for GDScript custom nodes.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Project Bindings Generator**: `tools/lapis/src/commands/bind/project.cr`
      # - **Live Specs**: `spec/suites/test_gdscript_interop.cr`
      #
      module B_GDSCRIPT_INTEROP
        # **Interoperability Modalities**: Dynamic reflection calls vs compile-time strongly-typed project bindings.
        #
        # #### Key Topics & Information
        #
        # - Dynamic calls: node.call("my_method", *args) with Variant marshaling
        # - Strongly-typed project bindings: Generated Crystal classes for all project GDScript scripts
        # - Cross-language signals: Subscribing to GDScript signals in Crystal and vice versa
        #
        def self.topic_00_interop_modes : Nil; end

        # **Automated Typed Project Bindings (lapis bind)**: Generating strongly-typed Crystal wrappers for GDScript custom nodes.
        #
        # When you run:
        # ```bash
        # lapis bind
        # ```
        # Lapis inspects all `.gd` scripts in your project and generates typed Crystal wrapper classes under `src/generated/project_nodes/`.
        #
        # #### Calling GDScript from Crystal:
        # ```crystal
        # # Strongly typed GDScript interop:
        # inventory = get_node("Inventory").as(GDScript::InventorySystem)
        # inventory.add_item("potion_health", 5) # Type-checked at compile time!
        # ```
        #
        # #### Calling Crystal from GDScript:
        # ```gdscript
        # var player = $Player # Crystal node registered in ClassDB
        # player.take_damage(25) # Calls Crystal def take_damage directly!
        # ```
        #
        def self.topic_01_typed_project_bindings : Nil; end
      end
    end
  end
end
{% end %}
