# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module F_SCRIPTING_AND_INTEROPERABILITY
      # # Doc Comments & Godot In-Editor F1 Help
      #
      # Comprehensive guide to how Lapis automatically harvests regular Crystal `# comments` above
      # classes, properties, signals, and methods at compile-time and injects them into Godot's F1 Help.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Documentation Harvesting Invariants</strong></td>
      #       <td><code>.topic_00_harvesting_features</code></td>
      #       <td>Automatic zero-overhead doc extraction into Godot's native DocData XML engine.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Doc Comment Authoring Syntax</strong></td>
      #       <td><code>.topic_01_authoring_syntax</code></td>
      #       <td>Formatting comments for optimal rendering in both Crystal Docs and Godot EditorHelp.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Editor Doc Engine**: `src/bridge/editor_doc.hpp`
      # - **Live Specs**: `spec/suites/test_editor_signals.cr`
      #
      module C_DOC_COMMENTS_AND_F1_HELP
        # **Documentation Harvesting Invariants**: Automatic zero-overhead doc extraction into Godot's native DocData XML engine.
        #
        # #### Key Topics & Information
        #
        # - Zero manual XML authoring: Write regular Crystal # comments above definitions
        # - Class, property, method, and signal descriptions are extracted at compile-time
        # - Injected into Godot's EditorHelp XML database on bridge initialization
        # - Full offline F1 Help and hover Inspector tooltips in Godot Editor
        #
        def self.topic_00_harvesting_features : Nil; end

        # **Doc Comment Authoring Syntax**: Formatting comments for optimal rendering in both Crystal Docs and Godot EditorHelp.
        #
        # ```crystal
        # # Player character with physics movement, health tracking, and abilities.
        # node Player < CharacterBody3D do
        #   # Movement speed in meters per second.
        #   @[Export]
        #   property speed : Float32 = 7.0_f32
        #
        #   # Emitted when player health drops to zero.
        #   signal died
        #
        #   # Applies raw physical impulse to character body.
        #   def apply_impulse(force : Vector3) : Void
        #   end
        # end
        # ```
        #
        # When compiled into `game.dll`, `crystal_bridge.dll` extracts these docstrings and registers them with Godot's `EditorHelp`. Pressing **F1** inside the Godot Editor and searching for `Player` will display this exact manual!
        #
        def self.topic_01_authoring_syntax : Nil; end
      end
    end
  end
end
{% end %}
