# ==============================================================================
# MyAddon::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module MyAddon
  # The `MyAddon::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 1 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>A_OVERVIEW</code></td>
  #       <td><strong>Addon Architecture & Extension Lifecycle</strong></td>
  #       <td>How your redistributable Godot GDExtension addon is structured, compiled, and loaded by Godot.</td>
  #     </tr>
  #     <tr>
  #       <td><code>B_CUSTOM_NODES</code></td>
  #       <td><strong>Custom Nodes & Inspector Properties</strong></td>
  #       <td>Exporting custom Control and Node classes to Godot's ClassDB with typed signals and properties.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### MyAddon Quick Start:
    # ```bash
    # make docs        # Build offline HTML documentation site in docs/
    # make test        # Execute specifications and test suites
    # make all         # Build and verify all targets
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::A_OVERVIEW`: **Addon Architecture & Extension Lifecycle** &mdash; How your redistributable Godot GDExtension addon is structured, compiled, and loaded by Godot.
    # - `A_GETTING_STARTED::B_CUSTOM_NODES`: **Custom Nodes & Inspector Properties** &mdash; Exporting custom Control and Node classes to Godot's ClassDB with typed signals and properties.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::A_OVERVIEW`: **Addon Architecture & Extension Lifecycle** &mdash; How your redistributable Godot GDExtension addon is structured, compiled, and loaded by Godot.
    # - `A_GETTING_STARTED::B_CUSTOM_NODES`: **Custom Nodes & Inspector Properties** &mdash; Exporting custom Control and Node classes to Godot's ClassDB with typed signals and properties.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/a_overview"
require "./docs/a_getting_started/b_custom_nodes"

alias Docs = ::MyAddon::Docs
alias Godot::Docs = ::MyAddon::Docs
{% end %}
