# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module G_DEBUGGING_AND_DIAGNOSTICS
      # # Native radare2 Debugging, Decompilation & Gutter Breakpoints
      #
      # Comprehensive guide to debugging Crystal game code running inside Godot using the radare2
      # native debugger and cradare2 engine, setting line-level breakpoints, decompiling functions on the fly,
      # and coordinating multiplayer sessions in lockstep.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Debugger & Decompiler Capabilities</strong></td>
      #       <td><code>.topic_00_debugging_features</code></td>
      #       <td>In-editor gutter breakpoints, native pseudo-C decompilation (pdc), disassembly (pdf), and PDB/DWARF symbol resolution.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Launching Game or Editor under radare2</strong></td>
      #       <td><code>.topic_01_launching_under_radare2</code></td>
      #       <td>Running lapis run -d or lapis editor -d from command line or IDE.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Debugger Driver**: `src/libgodot/debugger/radare_driver.cr`
      # - **Decompiler**: `src/libgodot/debugger/decompiler.cr`
      # - **Crash Forensics**: `src/libgodot/debugger/plugin_forensics.cr`
      # - **Live Specs**: `spec/radare_driver_spec.cr`
      #
      module A_RADARE2_NATIVE_DEBUGGING
        # **Debugger & Decompiler Capabilities**: In-editor gutter breakpoints, native pseudo-C decompilation (pdc), disassembly (pdf), and PDB/DWARF symbol resolution.
        #
        # #### Key Topics & Information
        #
        # - Set gutter breakpoints directly inside .cr files in Godot Editor or IDEs
        # - Zero-dependency native pseudo-C decompilation (pdc) and side-by-side assembly (pdca)
        # - Full symbol resolution for Crystal functions, Godot C-API, and C++ loader bridge
        # - Multiplayer cooperative lockstep pause/resume across Server and Client instances
        # - Automated dead-pointer detection via Godot ObjectDB 64-bit instance ID tracking
        #
        def self.topic_00_debugging_features : Nil; end

        # **Launching Game or Editor under radare2**: Running lapis run -d or lapis editor -d from command line or IDE.
        #
        # #### Method 1: Command Line (Lapis CLI)
        # ```bash
        # # Run standalone game under radare2:
        # lapis run --debug
        #
        # # Launch Godot Editor under radare2:
        # lapis editor --debug
        #
        # # Decompile functions or classes into pseudo-C:
        # lapis decompile bin/game.dll "Player#_physics_process"
        # ```
        #
        # #### Method 2: Godot In-Editor Debugger
        # 1. Launch Godot Editor (`lapis editor`).
        # 2. The **Crystal (radare2)** panel appears automatically in the bottom debugger dock.
        # 3. Set breakpoints in the Godot Script Editor gutter.
        # 4. Press **F5** to run the project. When a breakpoint is hit, the 3-pane debugger interface displays call stacks, registers, and real-time decompiled pseudo-C!
        #
        def self.topic_01_launching_under_radare2 : Nil; end
      end
    end
  end
end
{% end %}
