# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module G_DEBUGGING_AND_DIAGNOSTICS
      # # Crash Diagnostics, Watchpoints & Memory Inspection
      #
      # Advanced diagnostic protocols for tracking down memory corruption, illegal writes,
      # stack overflows, and segmentation faults using radare2 hardware watchpoints, GDExtension crash forensics,
      # and Godot ObjectDB monotonic instance ID validation.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Diagnostic Instruments</strong></td>
      #       <td><code>.topic_00_diagnostic_tools</code></td>
      #       <td>Hardware watchpoints, automated crash forensics, and memory dumping.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Catching Illegal Writes with Hardware Watchpoints in radare2</strong></td>
      #       <td><code>.topic_01_hardware_watchpoints</code></td>
      #       <td>Breaking execution at the exact CPU instruction performing memory corruption.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Crash Handler**: `src/libgodot/crash_handler.cr`
      # - **Crash Forensics**: `src/libgodot/debugger/plugin_forensics.cr`
      # - **Skill**: `cradare2-debugger`
      #
      module B_CRASH_HANDLER_AND_WATCHPOINTS
        # **Diagnostic Instruments**: Hardware watchpoints, automated crash forensics, and memory dumping.
        #
        # #### Key Topics & Information
        #
        # - Automated crash forensics classifying memory faults across game, plugin, bridge, and engine
        # - Hardware data write watchpoints in radare2 (rw / drw commands)
        # - Godot ObjectDB dead-pointer detection preventing unhandled ACCESS_VIOLATION crashes
        #
        def self.topic_00_diagnostic_tools : Nil; end

        # **Catching Illegal Writes with Hardware Watchpoints in radare2**: Breaking execution at the exact CPU instruction performing memory corruption.
        #
        # If a pointer or variable address is being corrupted mysteriously across frames:
        #
        # 1. In radare2, find the address of the target variable or memory location:
        #    ```text
        #    [0x...]> ?v &my_variable
        #    0x0000021b3759c2f0
        #    ```
        # 2. Set a hardware write watchpoint on that memory location:
        #    ```text
        #    [0x...]> rw 0x0000021b3759c2f0
        #    ```
        # 3. Continue execution (`dc`).
        # 4. As soon as any thread or machine instruction writes to that address, the CPU traps immediately and radare2 pauses at the exact offending machine instruction!
        #
        def self.topic_01_hardware_watchpoints : Nil; end
      end
    end
  end
end
{% end %}
