# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module E_MEMORY_SAFETY_AND_ENGINE_INTERNALS
      # # Godot ObjectDB & Monotonic Instance IDs
      #
      # Technical analysis of Godot's ObjectDB internal architecture, monotonic 64-bit instance IDs,
      # and how Lapis prevents heap address aliasing across recycled C++ allocations.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>ObjectDB Invariants</strong></td>
      #       <td><code>.topic_00_core_concepts</code></td>
      #       <td>Monotonic 64-bit IDs, instance lookup, and pointer validity.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>The Recycled Pointer Hazard</strong></td>
      #       <td><code>.topic_01_pointer_aliasing_hazard</code></td>
      #       <td>Why storing raw C++ pointers causes silent memory corruption.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Object Implementation**: `src/libgodot/object.cr`
      # - **Bridge Safety**: `src/bridge/crystal_bridge.cpp`
      #
      module A_OBJECTDB_AND_MONOTONIC_IDS
        # **ObjectDB Invariants**: Monotonic 64-bit IDs, instance lookup, and pointer validity.
        #
        # #### Key Topics & Information
        #
        # - Every Godot Object is assigned a strictly increasing 64-bit integer ID
        # - Instance IDs never collide across deleted and newly allocated objects
        # - Native address validation via gd_util_is_instance_id_valid
        #
        def self.topic_00_core_concepts : Nil; end

        # **The Recycled Pointer Hazard**: Why storing raw C++ pointers causes silent memory corruption.
        #
        # In native C and C++, the operating system allocator frequently reuses freed memory addresses:
        # 1. Node `A` is allocated at pointer address `0x1000`.
        # 2. Node `A` is freed (`queue_free`).
        # 3. A new Node `B` is allocated and assigned the recycled address `0x1000`.
        # 4. If a Crystal wrapper only tracks `0x1000`, calling a method on `A` inadvertently mutates `B`!
        #
        # #### Lapis Solution:
        # Every `Godot::Object` stores its monotonic `@instance_id` (e.g. `9223372041468510447`). When `A` is freed, its instance ID is permanently retired by Godot. Querying `ObjectDB.get_instance(@instance_id)` safely returns null!
        #
        def self.topic_01_pointer_aliasing_hazard : Nil; end
      end
    end
  end
end
{% end %}
