# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module E_MEMORY_SAFETY_AND_ENGINE_INTERNALS
      # # Dead-Pointer Protection & Access Violation Defense
      #
      # Comprehensive guide to Lapis's active dead-pointer protection mechanism, preventing
      # segmentation faults (`ACCESS_VIOLATION / 0xC0000005`) when nodes are freed by GDScript or the engine.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Dead-Pointer Defense Primitives</strong></td>
      #       <td><code>.topic_00_defense_primitives</code></td>
      #       <td>Methods available on every Godot::Object wrapper for defensive lifetime inspection.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>The Dead-Pointer Hazard</strong></td>
      #       <td><code>.topic_01_the_segfault_problem</code></td>
      #       <td>How standard bindings crash without stack traces and how Lapis defends against it.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Defensive Coding Patterns</strong></td>
      #       <td><code>.topic_02_defensive_coding_patterns</code></td>
      #       <td>Checking #alive? when holding references to transient entities.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Object Implementation**: `src/libgodot/object.cr`
      # - **Live Specs**: `spec/suites/test_safety.cr`
      #
      module B_DEAD_POINTER_PROTECTION
        # **Dead-Pointer Defense Primitives**: Methods available on every Godot::Object wrapper for defensive lifetime inspection.
        #
        # #### Key Topics & Information
        #
        # - object.alive? : Returns true if native C++ engine object is still valid
        # - object.destroyed? : Returns true if node was freed in GDScript or Godot
        # - object.check_alive! : Raises Godot::DisposedObjectError if freed
        #
        def self.topic_00_defense_primitives : Nil; end

        # **The Dead-Pointer Hazard**: How standard bindings crash without stack traces and how Lapis defends against it.
        #
        # If an entity (e.g. an enemy) is deleted in GDScript via `queue_free()`, standard C bindings retain a dangling raw pointer. Dereferencing this pointer triggers an immediate unrecoverable crash:
        # `ACCESS_VIOLATION (0xC0000005)`
        #
        # In Lapis, every virtual dispatch and reflection call invokes `#check_alive!`:
        # ```crystal
        # def check_alive! : Void
        #   return if @pointer.null?
        #   unless Bridge.is_instance_id_valid(@instance_id)
        #     @pointer = Pointer(Void).null
        #     raise Godot::DisposedObjectError.new("Cannot access disposed Godot object")
        #   end
        # end
        # ```
        #
        # Instead of crashing the game, you get a clean, catchable Crystal exception with full stack trace!
        #
        def self.topic_01_the_segfault_problem : Nil; end

        # **Defensive Coding Patterns**: Checking #alive? when holding references to transient entities.
        #
        # ```crystal
        # node Tower < Node2D do
        #   @target : Enemy? = nil
        #
        #   def _physics_process(delta : Float64) : Void
        #     # Check alive before firing:
        #     if enemy = @target
        #       if enemy.alive?
        #         fire_at(enemy.global_position)
        #       else
        #         @target = nil # Clear stale reference
        #       end
        #     end
        #   end
        # end
        # ```
        #
        def self.topic_02_defensive_coding_patterns : Nil; end
      end
    end
  end
end
{% end %}
