# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module E_MEMORY_SAFETY_AND_ENGINE_INTERNALS
      # # Boehm GC vs Godot Reference Counting
      #
      # In-depth architectural comparison between Crystal's Boehm-Demers-Weiser Garbage Collector
      # and Godot's native reference-counting system (`RefCounted`, `Resource`).
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>The Two Memory Models</strong></td>
      #       <td><code>.topic_00_memory_paradigms</code></td>
      #       <td>Crystal heap objects vs Godot native reference-counted instances.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>RefCounted & Resource Lifecycle Rules</strong></td>
      #       <td><code>.topic_01_refcounted_rules</code></td>
      #       <td>Never call manual .destroy on RefCounted or Resource instances.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Object Implementation**: `src/libgodot/object.cr`
      # - **Bridge GC Hook**: `src/bridge/gc_hook.hpp`
      #
      module C_BOEHM_GC_VS_REFCOUNTING
        # **The Two Memory Models**: Crystal heap objects vs Godot native reference-counted instances.
        #
        # #### Key Topics & Information
        #
        # - Crystal Objects: Managed by Boehm GC (GC.collect)
        # - Godot Nodes: Managed by SceneTree ownership (queue_free)
        # - Godot Resources: Managed by atomic reference counters (reference/unreference)
        #
        def self.topic_00_memory_paradigms : Nil; end

        # **RefCounted & Resource Lifecycle Rules**: Never call manual .destroy on RefCounted or Resource instances.
        #
        # #### Rule 1: Never Call .destroy on RefCounted Resources
        # `RefCounted` and `Resource` instances (e.g. `Texture2D`, `Shader`, `AudioStream`) are freed automatically when their reference count drops to 0. Calling manual `.destroy` destroys native C++ state prematurely, crashing Godot when the counter decrements.
        #
        # #### Rule 2: Standalone Nodes Must Be Explicitly Freed
        # Nodes created via `Godot.create(Godot::Node2D)` that are **never** added to the scene tree via `add_child` are not owned by Godot. To prevent C++ memory leaks, you must explicitly call `node.destroy` when done with them.
        #
        def self.topic_01_refcounted_rules : Nil; end
      end
    end
  end
end
{% end %}
