# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module I_ARCHITECTURE_AND_EXTENSIONS
      # # The Dual-Paradigm Execution Model
      #
      # Comprehensive architectural deep dive into Lapis's dual execution paradigms, comparing
      # in-editor GDExtension dynamic loading with standalone LibGodot host execution.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Comparative Architectural Matrix</strong></td>
      #       <td><code>.topic_00_paradigm_comparison</code></td>
      #       <td>Host binary, loading mechanics, GC init, and primary use cases.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Mode A: GDExtension Dynamic Loading</strong></td>
      #       <td><code>.topic_01_mode_a_mechanics</code></td>
      #       <td>How Godot loads crystal_bridge.dll and bootstraps Crystal's runtime.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Mode B: Standalone LibGodot Host</strong></td>
      #       <td><code>.topic_02_mode_b_mechanics</code></td>
      #       <td>Crystal executable hosting the Godot engine directly.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Architecture Spec**: `AGENTS.md`
      # - **Bridge Source**: `src/bridge/crystal_bridge.cpp`
      #
      module A_DUAL_PARADIGM_MODEL
        # **Comparative Architectural Matrix**: Host binary, loading mechanics, GC init, and primary use cases.
        #
        # #### Key Topics & Information
        #
        # - Mode A: Host is godot.exe, dynamic DLL loading via GDExtension bridge
        # - Mode B: Host is game.exe, statically or dynamically linked LibGodot host
        # - Mode A features instant F5 hot reloading via shadow copies
        # - Mode B provides minimal memory footprint and zero GDExtension loader overhead
        #
        def self.topic_00_paradigm_comparison : Nil; end

        # **Mode A: GDExtension Dynamic Loading**: How Godot loads crystal_bridge.dll and bootstraps Crystal's runtime.
        #
        # In Mode A (Development & Editor):
        # 1. Godot boots and parses `addons/crystal_integration/crystal.gdextension`.
        # 2. Godot calls `crystal_library_init` in `crystal_bridge.dll`.
        # 3. The bridge initializes Boehm GC (`GC_init()`) and CRT hooks.
        # 4. The bridge loads `bin/game.dll` (via shadow copy on Windows).
        # 5. The bridge passes function pointers to `crystal_godot_init`.
        # 6. Custom Crystal nodes register with Godot's `ClassDB`.
        #
        def self.topic_01_mode_a_mechanics : Nil; end

        # **Mode B: Standalone LibGodot Host**: Crystal executable hosting the Godot engine directly.
        #
        # In Mode B (Production Shipping & Headless Runners):
        # 1. The OS executes `bin/game.exe` (a native Crystal binary).
        # 2. The Crystal CRT initializes Boehm GC natively.
        # 3. The Crystal executable dynamically links `bin/libgodot.dll`.
        # 4. Crystal invokes `libgodot_create_godot_instance` and drives the engine main loop.
        # 5. Provides a self-contained, high-performance runtime for dedicated servers and production exports.
        #
        def self.topic_02_mode_b_mechanics : Nil; end
      end
    end
  end
end
{% end %}
