# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module I_ARCHITECTURE_AND_EXTENSIONS
      # # Native C++ Loader Bridge Architecture
      #
      # Technical analysis of `src/bridge/crystal_bridge.cpp`, resolving Godot GDExtension interface
      # tables and bridging them across flat C-ABI boundaries into Crystal.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Bridge Responsibilities</strong></td>
      #       <td><code>.topic_00_bridge_responsibilities</code></td>
      #       <td>GC initialization, C-ABI flattening, ClassDB dispatch, and crash isolation.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>The BridgeAPI Function Pointer Table</strong></td>
      #       <td><code>.topic_01_function_pointer_table</code></td>
      #       <td>How Crystal receives direct Godot engine entry points.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Bridge Source**: `src/bridge/crystal_bridge.cpp`
      # - **Module Loader**: `src/bridge/module_loader.hpp`
      # - **GDExtension API**: `src/bridge/gdextension_api.hpp`
      #
      module B_CPP_BRIDGE_LOADER
        # **Bridge Responsibilities**: GC initialization, C-ABI flattening, ClassDB dispatch, and crash isolation.
        #
        # #### Key Topics & Information
        #
        # - Boehm GC initialization (GC_init) before any Crystal code runs
        # - Flattens Godot's C++ virtual dispatches into direct C function pointers
        # - Tracks loaded modules and handles shadow DLL lifecycle
        # - Guards entry points against concurrent re-initialization
        #
        def self.topic_00_bridge_responsibilities : Nil; end

        # **The BridgeAPI Function Pointer Table**: How Crystal receives direct Godot engine entry points.
        #
        # During initialization, `crystal_bridge.cpp` populates a flat `BridgeAPI` structure containing direct function pointers to Godot engine entry points:
        # - `gd_classdb_register_extension_class`
        # - `gd_classdb_register_extension_class_method`
        # - `gd_classdb_register_extension_class_property`
        # - `gd_classdb_register_extension_class_signal`
        # - `gd_variant_get_ptr_utility_function`
        #
        # When `crystal_godot_init(&g_bridge_api)` is called, Crystal stores these function pointers in `Godot::Bridge`, bypassing all C++ ABI name mangling and calling engine routines at raw C speed!
        #
        def self.topic_01_function_pointer_table : Nil; end
      end
    end
  end
end
{% end %}
