# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in C:\Users\Ian\Documents\libgodot\docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Lapis
  module Docs
    module I_ARCHITECTURE_AND_EXTENSIONS
      # # Godot Engine Version Upgrade Guide
      #
      # Step-by-step engineering runbook for upgrading Lapis to target a new Godot engine release,
      # dumping API schemas, and updating the Crystal binding generator.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>The Upgrade Workflow</strong></td>
      #       <td><code>.topic_00_upgrade_steps</code></td>
      #       <td>Sequential steps to upgrade the targeted Godot engine version across Lapis.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Dumping Godot Extension API</strong></td>
      #       <td><code>.topic_01_dumping_api</code></td>
      #       <td>Extracting the JSON machine-readable API definition from Godot.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - **Engine Version Spec**: `godot-version.yml`
      # - **Binding Generator**: `src/libgodot/generator/`
      # - **Setup Command**: `tools/lapis/src/commands/setup.cr`
      #
      module D_GODOT_VERSION_UPGRADE
        # **The Upgrade Workflow**: Sequential steps to upgrade the targeted Godot engine version across Lapis.
        #
        # #### Key Topics & Information
        #
        # - 1. Update godot-version.yml with target version string and download URLs
        # - 2. Run lapis setup engine to acquire the new engine binary
        # - 3. Dump extension_api.json via godot.exe --dump-extension-api
        # - 4. Regenerate Crystal class bindings via make generate
        # - 5. Run make all to recompile bridge, test suites, and examples
        #
        def self.topic_00_upgrade_steps : Nil; end

        # **Dumping Godot Extension API**: Extracting the JSON machine-readable API definition from Godot.
        #
        # ```bash
        # # 1. Update version in godot-version.yml
        # # 2. Acquire new engine binary:
        # lapis setup engine
        #
        # # 3. Dump fresh extension API:
        # ./godot.exe --dump-extension-api
        #
        # # 4. Regenerate Crystal bindings:
        # make generate
        # ```
        #
        def self.topic_01_dumping_api : Nil; end
      end
    end
  end
end
{% end %}
